"""
    AZLegInfo

AZLegInfo is a package to get data conerning the Arizona State Legislature, and to some extent, the
"""

module AZLegInfo
using DataFrames, HTTP, JSON3, JavaCall,  Downloads

export getSessions, getBillId, getBillInfo, getBillPositions_JSON, extract_tables_from_pdf

# Module-level so the JVM is initialized at most once per Julia session.
# JNI does not support tearing down and recreating a JVM in the same
# process, so this state must not be reset on every call to
# extract_tables_from_pdf.
const _tabula_tmpdir = Ref{Union{Nothing,String}}(nothing)
const _tabula_jar = Ref{Union{Nothing,String}}(nothing)
const _tabula_initialized = Ref(false)

function getSessions()::DataFrame
    """
    Returns a DataFrame with information for every Arizona State Legislative Session (avaliable through the API)

    Returns:
    A DataFrame with information for every Arizona State Legislative Session (avaliable through the API)

    """
    SessionIDs = DataFrame()


    ID = 0
    emptySessionIDs = 0

    while true
        ID += 1
        url = "https://apps.azleg.gov/api/Session/?sessionId=$ID"
        resp = HTTP.get(url)
        data = JSON3.read(String(resp.body))

        # Context: Some SessionID's are empty.
        # Allows for up to 100 empty SessionIDs
        if length(Array(data)) == 0
            if emptySessionIDs > 100
                break
            end
            emptySessionIDs += 1
        end
        # Append the current SessionID to the df
        append!(SessionIDs, DataFrame(data))
        end

    return SessionIDs
    end

function getBillInfo(billNumber::String, sessionID::Int)
    """
    Returns basic information aout a bill as a parsed JSON.

    Expects:
        billNumber is the Bill Number as a string (for example: SB1010)
        sessionID is the Session ID (see the function getSessions())
    """
    url="https://apps.azleg.gov/api/Bill/?billNumber=$billNumber&sessionId=$sessionID"
    resp = HTTP.get(url)
    return JSON3.parse(String(resp.body))
    end

function getBillId(billNumber::String, sessionID::Int)::Int
    """
    Returns a bill's identification number from its bill number (example: SB1010) and its session (see the getSessions() function)
    """
    billInfo = getBillInfo(billNumber, sessionID)
    return Int(billInfo["BillId"])
    end

function getBillPositions_JSON(billNumber::String, sessionID::Int)
    """
    Returns the RTS system positions for a particular bill as a JSON.

    Expects:
        billNumber is the Bill Number as a string (for example: SB1010)
        sessionID is the Session ID (see the function getSesions())

    Returns
        A JSON of the positions
    """
    billId = getBillId(billNumber, sessionID)
    url = "https://apps.azleg.gov/api/BillPosition/?id=$sessionID&billStatusId=$billId"
    resp = HTTP.get(url)
    return JSON3.parse(String(resp.body))
    end

function extract_tables_from_pdf(pdf_path::AbstractString)
    """
    Extracts Tables from a PDF

    The function downloads the .jar file for Tabula to a temporary location
    so that it is automatically deleted when no longer in use.

    Then it uses JavaCall to run Tabula and utilizes it to extract
    the tables from a PDF.

    It expects the PDFs to follow the provided format for legislative
    votes. Each page is first read in lattice mode (tables drawn with
    ruling lines); pages without ruled tables fall back to stream mode
    (whitespace-aligned columns) on each detected table area.

    On Linux and macOS, Julia must be started with the environment
    variable JULIA_COPY_STACKS=1 (e.g. `JULIA_COPY_STACKS=1 julia`),
    otherwise JavaCall refuses to run outside the root task, which
    includes Jupyter and Pluto. Do not set it on Windows.

    Expects:
        pdf_path is the path to the pdf

    Returns
       Tables as DataFrame, one row per table row, with columns named
       column_1, column_2, ... Header rows repeated on each page are kept.

    Citations:
      Text generated by ChatGPT, OpenAI, September 22, 2026, https://chatgpt.com/s/t_6ab2ce120dc88191becfac3228d8f310.
      Code revised by Claude Code, Anthropic, September 22, 2026, https://claude.ai/code/session_01SQ79sYVPmqwp7yFkriCVsL.
    """
    isfile(pdf_path) || throw(ArgumentError("No such file: $pdf_path"))

    TABULA_JAR_URL =
        "https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar"

    function cleanup_tabula()
        tmpdir = _tabula_tmpdir[]

        if tmpdir !== nothing && isdir(tmpdir)
            try
                rm(tmpdir; recursive=true, force=true)
            catch err
                @warn "Unable to remove temporary Tabula directory" exception=err
            end
        end

        _tabula_tmpdir[] = nothing
        _tabula_jar[] = nothing

        nothing
    end

    function initialize_tabula()
        _tabula_initialized[] && return

        # JavaCall.init() throws if another package already started the
        # JVM, and the classpath can no longer be extended at that point.
        if JavaCall.isloaded()
            @warn "JVM was already started elsewhere; Tabula must already be on its classpath"
            _tabula_initialized[] = true
            return
        end

        tmpdir = mktempdir()
        jar_path = joinpath(
            tmpdir,
            "tabula-1.0.5-jar-with-dependencies.jar",
        )

        try
            Downloads.download(TABULA_JAR_URL, jar_path)

            # The classpath must be configured before JVM initialization.
            JavaCall.addClassPath(jar_path)
            JavaCall.init()

            _tabula_tmpdir[] = tmpdir
            _tabula_jar[] = jar_path
            _tabula_initialized[] = true

            # Register cleanup once the JVM has been initialized.
            atexit(cleanup_tabula)

        catch
            rm(tmpdir; recursive=true, force=true)
            rethrow()
        end

        nothing
    end

    initialize_tabula()

    # JNI resolves methods by exact signature, so every jcall needs the
    # concrete Java class; a bare JavaObject has no signature.
    JFile = @jimport java.io.File
    JObject = @jimport java.lang.Object
    JList = @jimport java.util.List
    PDDocument = @jimport org.apache.pdfbox.pdmodel.PDDocument
    ObjectExtractor = @jimport technology.tabula.ObjectExtractor
    PageIterator = @jimport technology.tabula.PageIterator
    Page = @jimport technology.tabula.Page
    Table = @jimport technology.tabula.Table
    RectangularTextContainer = @jimport technology.tabula.RectangularTextContainer
    Rectangle = @jimport technology.tabula.Rectangle
    SpreadsheetExtractionAlgorithm =
        @jimport technology.tabula.extractors.SpreadsheetExtractionAlgorithm
    BasicExtractionAlgorithm =
        @jimport technology.tabula.extractors.BasicExtractionAlgorithm
    NurminenDetectionAlgorithm =
        @jimport technology.tabula.detectors.NurminenDetectionAlgorithm

    # PDDocument.load has no String overload, only File/InputStream/byte[].
    pdf_file = JFile((JString,), abspath(pdf_path))
    document = jcall(PDDocument, "load", PDDocument, (JFile,), pdf_file)

    jlist(list, T) = [convert(T, jcall(list, "get", JObject, (jint,), i))
                      for i in 0:(jcall(list, "size", jint, ()) - 1)]

    try
        spreadsheet = SpreadsheetExtractionAlgorithm(())
        basic = BasicExtractionAlgorithm(())
        detector = NurminenDetectionAlgorithm(())

        # Lattice mode for tables drawn with ruling lines; if it finds none,
        # fall back to stream mode (whitespace-aligned columns) on each
        # detected table area, so titles and headers outside the table
        # don't distort column detection.
        function page_tables(page)
            tables = filter(
                t -> jcall(t, "getRowCount", jint, ()) > 0,
                jlist(jcall(spreadsheet, "extract", JList, (Page,), page), Table),
            )
            isempty(tables) || return tables

            areas = jlist(jcall(detector, "detect", JList, (Page,), page), Rectangle)
            regions = isempty(areas) ? [page] :
                [jcall(page, "getArea", Page, (Rectangle,), a) for a in areas]

            reduce(vcat,
                   [jlist(jcall(basic, "extract", JList, (Page,), r), Table) for r in regions])
        end

        extractor = ObjectExtractor((PDDocument,), document)
        pages = jcall(extractor, "extract", PageIterator, ())

        all_rows = Vector{Vector{String}}()

        while Bool(jcall(pages, "hasNext", jboolean, ()))
            page = jcall(pages, "next", Page, ())

            for table in page_tables(page)
                for cells in jlist(jcall(table, "getRows", JList, ()), JList)
                    push!(all_rows, [
                        replace(jcall(cell, "getText", JString, ()), '\r' => ' ')
                        for cell in jlist(cells, RectangularTextContainer)
                    ])
                end
            end
        end

        isempty(all_rows) && return DataFrame()

        # Normalize rows because different tables may have
        # different numbers of columns.
        ncols = maximum(length, all_rows)

        for row in all_rows
            append!(
                row,
                fill("", ncols - length(row)),
            )
        end

        DataFrame(
            [
                getindex.(all_rows, i)
                for i in 1:ncols
            ],
            Symbol.(
                "column_" .* string.(1:ncols)
            ),
        )

    finally
        jcall(
            document,
            "close",
            Nothing,
            (),
        )
    end
end



end # module
