"""
    AZLegInfo

AZLegInfo is a package to get data conerning the Arizona State Legislature, and to some extent, the
"""

module AZLegInfo
using DataFrames, HTTP, JSON3, JavaCall,  Downloads

export getSessions, getBillId, getBillInfo, getBillPositions_JSON
function getSessions()::DataFrame
    """
    Returns a DataFrame with information for every Arizona State Legislative Session (avaliable through the API)

    Returns:
    A DataFrame with information for every Arizona State Legislative Session (avaliable through the API)

    """
    SessionIDs = DataFrame()


    ID = 0
    emptySessionIDs = 0

    while true
        ID += 1
        url = "https://apps.azleg.gov/api/Session/?sessionId=$ID"
        resp = HTTP.get(url)
        data = JSON3.read(String(resp.body))

        # Context: Some SessionID's are empty.
        # Allows for up to 100 empty SessionIDs
        if length(Array(data)) == 0
            if emptySessionIDs > 100
                break
            end
            emptySessionIDs += 1
        end
        # Append the current SessionID to the df
        append!(SessionIDs, DataFrame(data))
        end

    return SessionIDs
    end

function getBillInfo(billNumber::String, sessionID::Int)
    """
    Returns basic information aout a bill as a parsed JSON.

    Expects:
        billNumber is the Bill Number as a string (for example: SB1010)
        sessionID is the Session ID (see the function getSessions())
    """
    url="https://apps.azleg.gov/api/Bill/?billNumber=$billNumber&sessionId=$sessionID"
    resp = HTTP.get(url)
    return JSON3.parse(String(resp.body))
    end

function getBillId(billNumber::String, sessionID::Int)::Int
    """
    Returns a bill's identification number from its bill number (example: SB1010) and its session (see the getSessions() function)
    """
    billInfo = getBillInfo(billNumber, sessionID)
    return Int(billInfo["BillId"])
    end

function getBillPositions_JSON(billNumber::String, sessionID::Int)
    """
    Returns the RTS system positions for a particular bill as a JSON.

    Expects:
        billNumber is the Bill Number as a string (for example: SB1010)
        sessionID is the Session ID (see the function getSesions())

    Returns
        A JSON of the positions
    """
    billId = getBillId(billNumber, sessionID)
    url = "https://apps.azleg.gov/api/BillPosition/?id=$sessionID&billStatusId=$billId"
    resp = HTTP.get(url)
    return JSON3.parse(String(resp.body))
    end

function extract_tables_from_pdf(pdf_path::AbstractString)
    """
    Extracts Tables from a PDF

    The function downloads the .jar file for Tabula to a temporary location
    so that it is automatically deleted when no longer in use.

    Then it uses JavaCall to run Tabula and utilizes it to extract
    the tables from a PDF.

    It expects the PDFs to follow the provided format for legislative
    votes.

    Expects:
        pdf_path is the path to the pdf

    Returns
       Tables as DataFrame

    Citations:
      Text generated by ChatGPT, OpenAI, September 22, 2026, https://chatgpt.com/s/t_6ab2ce120dc88191becfac3228d8f310.
    """
    TABULA_JAR_URL =
        "https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar"

    # Process-local state captured by the nested functions.
    tabula_tmpdir = Ref{Union{Nothing,String}}(nothing)
    tabula_jar = Ref{Union{Nothing,String}}(nothing)
    tabula_initialized = Ref(false)

    function cleanup_tabula()
        tmpdir = tabula_tmpdir[]

        if tmpdir !== nothing && isdir(tmpdir)
            try
                rm(tmpdir; recursive=true, force=true)
            catch err
                @warn "Unable to remove temporary Tabula directory" exception=err
            end
        end

        tabula_tmpdir[] = nothing
        tabula_jar[] = nothing

        nothing
    end

    function initialize_tabula()
        tabula_initialized[] && return

        tmpdir = mktempdir()
        jar_path = joinpath(
            tmpdir,
            "tabula-1.0.5-jar-with-dependencies.jar",
        )

        try
            Downloads.download(TABULA_JAR_URL, jar_path)

            # The classpath must be configured before JVM initialization.
            JavaCall.addClassPath(jar_path)
            JavaCall.init()

            tabula_tmpdir[] = tmpdir
            tabula_jar[] = jar_path
            tabula_initialized[] = true

            # Register cleanup once the JVM has been initialized.
            atexit(cleanup_tabula)

        catch
            rm(tmpdir; recursive=true, force=true)
            rethrow()
        end

        nothing
    end

    initialize_tabula()

    # Java classes used by Tabula.
    PDDocument =
        @jimport org.apache.pdfbox.pdmodel.PDDocument

    SpreadsheetExtractionAlgorithm =
        @jimport technology.tabula.extractors.SpreadsheetExtractionAlgorithm

    ObjectExtractor =
        @jimport technology.tabula.ObjectExtractor

    RectangularTextContainer =
        @jimport technology.tabula.RectangularTextContainer

    document = jcall(
        PDDocument,
        "load",
        PDDocument,
        (JString,),
        pdf_path,
    )

    try
        sea = SpreadsheetExtractionAlgorithm(())

        extractor = ObjectExtractor(
            (PDDocument,),
            document,
        )

        pages = jcall(
            extractor,
            "extract",
            JavaObject,
            (),
        )

        all_rows = Vector{Vector{String}}()

        while jcall(
            pages,
            "hasNext",
            jboolean,
            (),
        )
            page = jcall(
                pages,
                "next",
                JavaObject,
                (),
            )

            tables = jcall(
                sea,
                "extract",
                JavaObject,
                (JavaObject,),
                page,
            )

            n_tables = jcall(
                tables,
                "size",
                jint,
                (),
            )

            for table_idx in 0:(n_tables - 1)
                table = jcall(
                    tables,
                    "get",
                    JavaObject,
                    (jint,),
                    table_idx,
                )

                rows = jcall(
                    table,
                    "getRows",
                    JavaObject,
                    (),
                )

                n_rows = jcall(
                    rows,
                    "size",
                    jint,
                    (),
                )

                for row_idx in 0:(n_rows - 1)
                    cells = jcall(
                        rows,
                        "get",
                        JavaObject,
                        (jint,),
                        row_idx,
                    )

                    n_cells = jcall(
                        cells,
                        "size",
                        jint,
                        (),
                    )

                    row = String[]

                    for cell_idx in 0:(n_cells - 1)
                        cell = jcall(
                            cells,
                            "get",
                            RectangularTextContainer,
                            (jint,),
                            cell_idx,
                        )

                        text = jcall(
                            cell,
                            "getText",
                            JString,
                            (),
                        )

                        push!(
                            row,
                            replace(
                                bytestring(text),
                                '\r' => ' ',
                            ),
                        )
                    end

                    push!(all_rows, row)
                end
            end
        end

        isempty(all_rows) && return DataFrame()

        # Normalize rows because different tables may have
        # different numbers of columns.
        ncols = maximum(length, all_rows)

        for row in all_rows
            append!(
                row,
                fill("", ncols - length(row)),
            )
        end

        DataFrame(
            [
                getindex.(all_rows, i)
                for i in 1:ncols
            ],
            Symbol.(
                "column_" .* string.(1:ncols)
            ),
        )

    finally
        jcall(
            document,
            "close",
            Nothing,
            (),
        )
    end
end



end # module
