"""
    PDFText

Reads the text of a PDF, and where each word is on the page, in pure Julia.

It implements the parts of the PDF specification (ISO 32000-1) needed to find
the text of a page:

- the file structure: cross-reference tables and streams, object streams and
  incremental updates, and rebuilding the cross-reference data by scanning the
  file when it is damaged;
- the stream filters FlateDecode (decompressed by the pure-Julia Inflate
  package), LZWDecode, ASCIIHexDecode, ASCII85Decode and RunLengthDecode;
- fonts: simple fonts with WinAnsi, MacRoman or Standard encodings,
  /Differences, the encodings built into Type 1 fonts, and the widths of the
  standard Helvetica, Times and Courier fonts; composite (Type0) fonts with
  Identity or embedded CMaps, including vertical ones; ToUnicode CMaps and
  glyph widths;
- the text operators of content streams, including text inside form XObjects,
  on pages that are rotated or whose /MediaBox does not start at 0, 0.

It does not render anything, decrypt encrypted PDFs, or read text that exists
only in images (scans). Damaged parts of a file are skipped with a warning.

Citations:
  Code generated by Claude Code, Anthropic, September 24, 2026, https://claude.ai/code/session_019awDnsGJAcXbzPNQg6VhqU.
"""
module PDFText

using Inflate

# ---------------------------------------------------------------------------
# PDF objects
#
# null is `nothing`, booleans are Bool, numbers are Int or Float64, names are
# Symbols, strings are Vector{UInt8} (their bytes; what they mean depends on
# the font), arrays are Vector{Any} and dictionaries are Dict{Symbol,Any}.
# ---------------------------------------------------------------------------

"A reference to the indirect object `num gen obj` (written `num gen R`)."
struct Ref
    num::Int
    gen::Int
end

"A stream object: its dictionary and its still-encoded bytes."
struct Stream
    dict::Dict{Symbol,Any}
    data::Vector{UInt8}
end

"A bare word such as `obj`, `R`, `true` or a content stream operator like `Tj`."
struct Keyword
    word::String
end

const EOF = Keyword("")
const ARRAY_START = Keyword("[")
const ARRAY_END = Keyword("]")
const DICT_START = Keyword("<<")
const DICT_END = Keyword(">>")

# ---------------------------------------------------------------------------
# Lexer (PDF 32000-1:2008, section 7.2 and 7.3)
# ---------------------------------------------------------------------------

mutable struct Lexer
    data::Vector{UInt8}
    pos::Int  # index of the next byte to read
end

iswhite(b::UInt8) = b == 0x20 || b == 0x0a || b == 0x0d || b == 0x09 || b == 0x0c || b == 0x00
isdelimiter(b::UInt8) = b == UInt8('(') || b == UInt8(')') || b == UInt8('<') || b == UInt8('>') ||
                        b == UInt8('[') || b == UInt8(']') || b == UInt8('{') || b == UInt8('}') ||
                        b == UInt8('/') || b == UInt8('%')
isregular(b::UInt8) = !iswhite(b) && !isdelimiter(b)
isdigit_byte(b::UInt8) = UInt8('0') <= b <= UInt8('9')

function hexvalue(b::UInt8)
    UInt8('0') <= b <= UInt8('9') && return Int(b - UInt8('0'))
    UInt8('a') <= b <= UInt8('f') && return Int(b - UInt8('a')) + 10
    UInt8('A') <= b <= UInt8('F') && return Int(b - UInt8('A')) + 10
    return -1
end

"Skips whitespace and comments."
function skip_space!(lx::Lexer)
    d, p, n = lx.data, lx.pos, length(lx.data)
    while p <= n
        b = d[p]
        if iswhite(b)
            p += 1
        elseif b == UInt8('%')
            while p <= n && d[p] != 0x0a && d[p] != 0x0d
                p += 1
            end
        else
            break
        end
    end
    lx.pos = p
    return lx
end

"Reads one token: a number, name, string, keyword, or one of `[ ] << >>`."
function read_token(lx::Lexer)
    skip_space!(lx)
    d, p, n = lx.data, lx.pos, length(lx.data)
    p > n && return EOF
    b = d[p]
    if b == UInt8('/')
        q = p + 1
        name = UInt8[]
        while q <= n && isregular(d[q])
            # #xx is the byte with hexadecimal code xx
            if d[q] == UInt8('#') && q + 2 <= n && hexvalue(d[q+1]) >= 0 && hexvalue(d[q+2]) >= 0
                push!(name, UInt8(16 * hexvalue(d[q+1]) + hexvalue(d[q+2])))
                q += 3
            else
                push!(name, d[q])
                q += 1
            end
        end
        lx.pos = q
        return Symbol(String(name))
    elseif b == UInt8('(')
        return read_literal_string!(lx)
    elseif b == UInt8('<')
        if p < n && d[p+1] == UInt8('<')
            lx.pos = p + 2
            return DICT_START
        end
        return read_hex_string!(lx)
    elseif b == UInt8('>') && p < n && d[p+1] == UInt8('>')
        lx.pos = p + 2
        return DICT_END
    elseif b == UInt8('[')
        lx.pos = p + 1
        return ARRAY_START
    elseif b == UInt8(']')
        lx.pos = p + 1
        return ARRAY_END
    elseif isdelimiter(b)
        # A stray ")", ">", "{" or "}"; "{" and "}" only appear in PostScript
        # functions, which are not needed to read text.
        lx.pos = p + 1
        return Keyword(String([b]))
    end
    q = p
    while q <= n && isregular(d[q])
        q += 1
    end
    lx.pos = q
    return number_or_keyword(d, p, q - 1)
end

"Parses `d[p:q]` as an integer or real number, or else returns it as a Keyword."
function number_or_keyword(d::Vector{UInt8}, p::Int, q::Int)
    i = p
    negative = false
    if d[i] == UInt8('-') || d[i] == UInt8('+')
        negative = d[i] == UInt8('-')
        i += 1
    end
    whole = 0
    fraction = 0.0
    scale = 1.0
    digits = 0  # before the point
    point = false
    while i <= q
        b = d[i]
        if isdigit_byte(b)
            if point
                scale /= 10
                fraction += (b - UInt8('0')) * scale
            else
                whole = 10 * whole + (b - UInt8('0'))
                digits += 1
            end
        elseif b == UInt8('.') && !point
            point = true
        else
            return keyword(d, p, q)
        end
        i += 1
    end
    (digits > 0 || scale < 1) || return keyword(d, p, q)
    # More than 18 digits could overflow an Int; such numbers are read as reals.
    digits > 18 && return parse(Float64, String(d[p:q]))
    point || return negative ? -whole : whole
    value = whole + fraction
    return negative ? -value : value
end

# Keywords of up to 4 bytes, packed into a UInt32. They include every content
# stream operator, so reading an operator does not allocate a new String.
pack(bytes) = foldl((key, b) -> (key << 8) | UInt8(b), bytes; init = UInt32(0))

const KEYWORDS = Dict(pack(codeunits(w)) => Keyword(w) for w in split(
    "obj R n f true null b B b* B* BDC BI BMC BT BX c cm CS cs d d0 d1 Do DP EI EMC ET EX q Q " *
    "f* F G g gs h i ID j J K k l m M MP re RG rg ri s S SC sc SCN scn sh T* Tc Td TD Tf Tj TJ " *
    "TL Tm Tr Ts Tw Tz v w W W* y ' \""))

function keyword(d::Vector{UInt8}, p::Int, q::Int)
    if q - p < 4
        k = get(KEYWORDS, pack(view(d, p:q)), nothing)
        k === nothing || return k
    end
    return Keyword(String(d[p:q]))
end

"Reads a `(literal string)`, starting at its opening parenthesis."
function read_literal_string!(lx::Lexer)
    d, n = lx.data, length(lx.data)
    p = lx.pos + 1
    out = UInt8[]
    depth = 1
    while p <= n
        b = d[p]
        if b == UInt8('\\')
            p += 1
            p > n && break
            c = d[p]
            if c == UInt8('n')
                push!(out, 0x0a)
            elseif c == UInt8('r')
                push!(out, 0x0d)
            elseif c == UInt8('t')
                push!(out, 0x09)
            elseif c == UInt8('b')
                push!(out, 0x08)
            elseif c == UInt8('f')
                push!(out, 0x0c)
            elseif UInt8('0') <= c <= UInt8('7')
                # Up to three octal digits; overflow past one byte is ignored.
                value = 0
                k = 0
                while k < 3 && p <= n && UInt8('0') <= d[p] <= UInt8('7')
                    value = 8 * value + (d[p] - UInt8('0'))
                    p += 1
                    k += 1
                end
                push!(out, value % UInt8)
                continue
            elseif c == 0x0d
                # A backslash at the end of a line continues the string.
                p < n && d[p+1] == 0x0a && (p += 1)
            elseif c != 0x0a
                push!(out, c)  # \( \) \\ and unknown escapes are the character itself
            end
            p += 1
        elseif b == UInt8('(')
            depth += 1
            push!(out, b)
            p += 1
        elseif b == UInt8(')')
            depth -= 1
            p += 1
            depth == 0 && break
            push!(out, b)
        elseif b == 0x0d
            # An end of line (CR, LF or CRLF) inside a string is read as LF.
            push!(out, 0x0a)
            p += 1
            p <= n && d[p] == 0x0a && (p += 1)
        else
            push!(out, b)
            p += 1
        end
    end
    lx.pos = p
    return out
end

"Reads a `<hexadecimal string>`, starting at its `<`."
function read_hex_string!(lx::Lexer)
    d, n = lx.data, length(lx.data)
    p = lx.pos + 1
    out = UInt8[]
    high = -1
    while p <= n
        b = d[p]
        p += 1
        b == UInt8('>') && break
        v = hexvalue(b)
        v < 0 && continue  # whitespace
        if high < 0
            high = v
        else
            push!(out, UInt8(16 * high + v))
            high = -1
        end
    end
    high >= 0 && push!(out, UInt8(16 * high))  # a missing last digit is 0
    lx.pos = p
    return out
end

"""
Reads one object. In a file (`refs = true`) `num gen R` is read as a Ref;
content streams have no references, so there it would be three operands.
"""
read_object(lx::Lexer; refs::Bool = true) = finish_object(lx, read_token(lx), refs)

# Real PDFs nest arrays and dictionaries a few levels deep; a limit keeps a
# damaged file (such as 10 KB of "[") from overflowing the stack.
const MAX_NESTING = 100

function finish_object(lx::Lexer, token, refs::Bool, depth::Int = 0)
    if (token === ARRAY_START || token === DICT_START) && depth >= MAX_NESTING
        error("PDF arrays or dictionaries nested more than $MAX_NESTING deep")
    end
    if token === ARRAY_START
        items = Any[]
        while true
            t = read_token(lx)
            (t === ARRAY_END || t === EOF) && break
            # Integers are pushed as they are and joined into references
            # below, so an array of numbers is not read ahead three times.
            push!(items, t isa Int ? t : finish_object(lx, t, refs, depth + 1))
        end
        return refs ? join_references(items) : items
    elseif token === DICT_START
        dict = Dict{Symbol,Any}()
        while true
            key = read_token(lx)
            (key === DICT_END || key === EOF) && break
            key isa Symbol || continue  # skip anything malformed
            value = read_token(lx)
            (value === DICT_END || value === EOF) && break
            dict[key] = finish_object(lx, value, refs, depth + 1)
        end
        return dict
    elseif token isa Keyword
        token.word == "true" && return true
        token.word == "false" && return false
        token.word == "null" && return nothing
        return token
    elseif refs && token isa Int
        # `num gen R` is a reference.
        start = lx.pos
        gen = read_token(lx)
        if gen isa Int && read_token(lx) == Keyword("R")
            return Ref(token, gen)
        end
        lx.pos = start
    end
    return token
end

function join_references(items::Vector{Any})
    out = Any[]
    i = 1
    while i <= length(items)
        if i + 2 <= length(items) && items[i] isa Int && items[i+1] isa Int && items[i+2] == Keyword("R")
            push!(out, Ref(items[i], items[i+1]))
            i += 3
        else
            push!(out, items[i])
            i += 1
        end
    end
    return out
end

# ---------------------------------------------------------------------------
# Documents (section 7.5): finding objects through the cross-reference data
# ---------------------------------------------------------------------------

"""
A PDF file in memory. `xref` maps an object number to where the object is:
`(1, offset, generation)` for an object in the file, or `(2, stream, index)`
for an object inside the object stream with object number `stream`.
"""
mutable struct Document
    data::Vector{UInt8}
    xref::Dict{Int,NTuple{3,Int}}
    trailer::Dict{Symbol,Any}
    objects::Dict{Int,Any}
    object_streams::Dict{Int,Dict{Int,Any}}
    loading::Set{Int}  # objects being read, to stop reference cycles
    scanned::Union{Nothing,Dict{Int,NTuple{2,Int}}}  # scan_objects, once it has been needed
    quiet::Bool  # no warnings about damaged objects while the xref is checked or rebuilt
end

function Document(data::Vector{UInt8})
    doc = Document(data, Dict{Int,NTuple{3,Int}}(), Dict{Symbol,Any}(),
                   Dict{Int,Any}(), Dict{Int,Dict{Int,Any}}(), Set{Int}(), nothing, true)
    try
        read_cross_references!(doc)
        haskey(doc.trailer, :Root) || error("no /Root in the trailer")
        # A wrong offset usually shows up here, as the catalog not being found.
        resolve(doc, doc.trailer[:Root]) isa Dict || error("the /Root is not a dictionary")
    catch err
        # The cross-reference data is damaged, so the objects are found by
        # scanning the whole file, as PDF readers commonly do.
        err isa InterruptException && rethrow()
        rebuild_cross_references!(doc)
    finally
        doc.quiet = false
    end
    haskey(doc.trailer, :Encrypt) && error("Encrypted PDFs are not supported")
    return doc
end

"Follows a Ref to the object it points to; any other object is returned as is."
resolve(doc::Document, x) = x isa Ref ? get_object(doc, x.num) : x

"Looks up `key` in `dict`, following a Ref, and returns `default` if it is missing."
getvalue(doc::Document, dict::AbstractDict, key::Symbol, default = nothing) =
    something(resolve(doc, get(dict, key, nothing)), Some(default))

"""
The object with number `num`, or `nothing` if there is none. An object that
cannot be read (because the file is damaged) is also read as `nothing`, with a
warning, as other PDF readers do.
"""
function get_object(doc::Document, num::Int)
    haskey(doc.objects, num) && return doc.objects[num]
    entry = get(doc.xref, num, nothing)
    entry === nothing && return nothing
    num in doc.loading && error("PDF object $num refers to itself")
    push!(doc.loading, num)
    object = try
        if entry[1] == 1
            try
                read_indirect_object(doc, entry[2], num)
            catch err
                err isa InterruptException && rethrow()
                # A wrong offset in the xref: look for the object in the file.
                doc.scanned === nothing && (doc.scanned = scan_objects(doc.data))
                found = get(doc.scanned, num, nothing)
                (found === nothing || found[1] == entry[2]) && rethrow()
                read_indirect_object(doc, found[1], num)
            end
        else
            get(object_stream(doc, entry[2]), num, nothing)
        end
    catch err
        err isa InterruptException && rethrow()
        doc.quiet || @warn "Skipping PDF object $num, which cannot be read" exception = err
        nothing
    finally
        delete!(doc.loading, num)
    end
    doc.objects[num] = object
    return object
end

"Reads `num gen obj ... endobj` at the 0-based byte `offset`."
function read_indirect_object(doc::Document, offset::Int, num::Int)
    lx = Lexer(doc.data, offset + 1)
    found = read_token(lx)
    read_token(lx)
    read_token(lx) == Keyword("obj") || error("No object at byte $offset")
    found == num || error("Object $num is not at byte $offset")
    object = read_object(lx)
    if object isa Dict && read_token(lx) == Keyword("stream")
        return read_stream_data(doc, lx, object)
    end
    return object
end

"Reads the bytes after the keyword `stream`, which `lx` has just read."
function read_stream_data(doc::Document, lx::Lexer, dict::Dict{Symbol,Any})
    d, n = doc.data, length(doc.data)
    p = lx.pos
    # The keyword is followed by CRLF or LF (or, in some files, CR alone).
    p <= n && d[p] == 0x0d && (p += 1)
    p <= n && d[p] == 0x0a && (p += 1)
    len = try
        resolve(doc, get(dict, :Length, nothing))
    catch
        nothing
    end
    if len isa Integer && 0 <= len <= n - p + 1 && ends_stream(d, p + len)
        return Stream(dict, d[p:p+len-1])
    end
    # A wrong /Length: the data ends at the keyword `endstream`.
    r = findnext(b"endstream", d, p)
    r === nothing && error("A PDF stream has no end")
    q = first(r) - 1
    q >= p && d[q] == 0x0a && (q -= 1)
    q >= p && d[q] == 0x0d && (q -= 1)
    return Stream(dict, d[p:q])
end

"Whether `endstream` follows byte `p` (after an optional end of line)."
function ends_stream(d::Vector{UInt8}, p::Int)
    while p <= length(d) && iswhite(d[p])
        p += 1
    end
    return p + 8 <= length(d) && view(d, p:p+8) == b"endstream"
end

"""
The objects inside the object stream `num` (section 7.5.7), by object number.
A damaged object stream is read as empty, with a warning.
"""
function object_stream(doc::Document, num::Int)
    get!(doc.object_streams, num) do
        try
            read_object_stream(doc, num)
        catch err
            err isa InterruptException && rethrow()
            doc.quiet || @warn "Skipping PDF object stream $num, which cannot be read" exception = err
            Dict{Int,Any}()
        end
    end
end

function read_object_stream(doc::Document, num::Int)
    stream = get_object(doc, num)
    stream isa Stream || error("PDF object $num is not an object stream")
    data = decode(doc, stream)
    # Each object needs at least 4 bytes ("1 0 " in the header), which bounds /N.
    count = clamp(getvalue(doc, stream.dict, :N, 0), 0, length(data) ÷ 4)
    start = getvalue(doc, stream.dict, :First, 0)
    lx = Lexer(data, 1)
    header = Tuple{Int,Int}[]
    for _ in 1:count
        objnum, offset = read_token(lx), read_token(lx)
        (objnum isa Int && offset isa Int) || break  # a damaged header or /N
        push!(header, (objnum, offset))
    end
    objects = Dict{Int,Any}()
    for (objnum, offset) in header
        lx.pos = start + offset + 1
        objects[objnum] = read_object(lx)
    end
    return objects
end

"Finds the byte offset after the last `startxref` in the file."
function find_startxref(d::Vector{UInt8})
    r = findprev(b"startxref", d, length(d))
    r === nothing && error("No startxref")
    offset = read_token(Lexer(d, last(r) + 1))
    offset isa Int || error("No offset after startxref")
    return offset
end

"""
Reads every cross-reference section, newest first, following /Prev. Entries
from newer sections win; free entries are skipped, so an object listed as free
in the table of a hybrid file is still found in its /XRefStm stream.
"""
function read_cross_references!(doc::Document)
    offset = find_startxref(doc.data)
    seen = Set{Int}()
    while offset !== nothing && !(offset in seen)
        push!(seen, offset)
        lx = Lexer(doc.data, offset + 1)
        trailer = if read_token(lx) == Keyword("xref")
            t = read_xref_table!(doc, lx)
            # Hybrid files list the objects in object streams in a stream.
            hybrid = get(t, :XRefStm, nothing)
            hybrid isa Int && !(hybrid in seen) && (push!(seen, hybrid); read_xref_stream!(doc, hybrid))
            t
        else
            read_xref_stream!(doc, offset)
        end
        for (key, value) in trailer
            haskey(doc.trailer, key) || (doc.trailer[key] = value)
        end
        prev = get(trailer, :Prev, nothing)
        offset = prev isa Integer ? Int(prev) : nothing
    end
    return doc
end

"Reads a classic `xref` table (section 7.5.4) and returns its trailer dictionary."
function read_xref_table!(doc::Document, lx::Lexer)
    while true
        start = read_token(lx)
        start == Keyword("trailer") && break
        count = read_token(lx)
        # Each entry takes 20 bytes (19 in some damaged files; 18 leaves slack),
        # which bounds a subsection's count.
        (start isa Int && count isa Int && 0 <= count <= (length(doc.data) - lx.pos) ÷ 18) ||
            error("Damaged xref table")
        for num in start:start+count-1
            offset, gen, kind = read_token(lx), read_token(lx), read_token(lx)
            (offset isa Int && gen isa Int && (kind == Keyword("n") || kind == Keyword("f"))) ||
                error("Damaged xref table")
            if kind == Keyword("n") && offset > 0
                haskey(doc.xref, num) || (doc.xref[num] = (1, offset, gen))
            end
        end
    end
    trailer = read_object(lx)
    trailer isa Dict || error("Damaged trailer")
    return trailer
end

"Reads a cross-reference stream (section 7.5.8) and returns its dictionary."
function read_xref_stream!(doc::Document, offset::Int)
    lx = Lexer(doc.data, offset + 1)
    read_token(lx)
    read_token(lx)
    read_token(lx) == Keyword("obj") || error("No xref stream at byte $offset")
    dict = read_object(lx)
    (dict isa Dict && read_token(lx) == Keyword("stream")) || error("No xref stream at byte $offset")
    stream = read_stream_data(doc, lx, dict)
    data = decode(doc, stream)
    widths = Int[resolve(doc, w) for w in dict[:W]]
    # Every entry must use some bytes, or a huge /Size would loop without end.
    (length(widths) == 3 && all(>=(0), widths) && sum(widths) > 0) || error("Damaged xref stream")
    size = get(dict, :Size, 0)
    index = get(dict, :Index, Any[0, size])
    p = 1
    field(w, default) = w == 0 ? default : (v = 0; for _ in 1:w; v = 256v + data[p]; p += 1; end; v)
    for k in 1:2:length(index)-1
        for num in index[k]:index[k]+index[k+1]-1
            p + sum(widths) - 1 <= length(data) || break
            kind = field(widths[1], 1)
            a = field(widths[2], 0)
            b = field(widths[3], 0)
            if kind == 1 || kind == 2
                haskey(doc.xref, num) || (doc.xref[num] = (kind, a, b))
            end
        end
    end
    return dict
end

"""
Finds every `num gen obj` in the file, as a Dict from object number to its
0-based offset and generation. A later definition of an object wins, as it
would in an incremental update.
"""
function scan_objects(d::Vector{UInt8})
    found = Dict{Int,NTuple{2,Int}}()
    r = findnext(b"obj", d, 1)
    while r !== nothing
        p = first(r)
        # "obj" must be a whole word, after "num gen ".
        if (p + 3 > length(d) || !isregular(d[p+3])) && p > 1 && iswhite(d[p-1])
            q = p - 1
            while q >= 1 && iswhite(d[q]); q -= 1; end
            gen_end = q
            while q >= 1 && isdigit_byte(d[q]); q -= 1; end
            gen_start = q + 1
            while q >= 1 && iswhite(d[q]); q -= 1; end
            num_end = q
            while q >= 1 && isdigit_byte(d[q]); q -= 1; end
            num_start = q + 1
            if gen_start <= gen_end && num_start <= num_end && num_end < gen_start - 1 &&
               num_end - num_start < 18 && gen_end - gen_start < 18 && (q < 1 || !isregular(d[q]))
                num = parse(Int, String(d[num_start:num_end]))
                found[num] = (num_start - 1, parse(Int, String(d[gen_start:gen_end])))
            end
        end
        r = findnext(b"obj", d, p + 3)
    end
    return found
end

"""
Rebuilds the cross-reference data by scanning the file for objects, for files
whose cross-reference data is damaged.
"""
function rebuild_cross_references!(doc::Document)
    d = doc.data
    empty!(doc.xref)
    empty!(doc.objects)
    empty!(doc.object_streams)
    empty!(doc.trailer)
    doc.scanned = scan_objects(d)
    for (num, (offset, gen)) in doc.scanned
        doc.xref[num] = (1, offset, gen)
    end
    # Objects in object streams, and the trailer.
    for num in sort!(collect(keys(doc.xref)))
        object = get_object(doc, num)  # nothing if it cannot be read
        if object isa Stream
            type = get(object.dict, :Type, nothing)
            if type === :ObjStm
                inner_objects = object_stream(doc, num)
                isempty(inner_objects) && @warn "PDF object stream $num cannot be read; the objects in it are missing"
                for inner in keys(inner_objects)
                    haskey(doc.xref, inner) || (doc.xref[inner] = (2, num, 0))
                end
            elseif type === :XRef
                merge!(doc.trailer, object.dict)
            end
        elseif object isa Dict && get(object, :Type, nothing) === :Catalog
            doc.trailer[:Root] = Ref(num, 0)
        end
    end
    r = findprev(b"trailer", d, length(d))
    while r !== nothing
        t = try
            read_object(Lexer(d, last(r) + 1))
        catch
            nothing
        end
        if t isa Dict && haskey(t, :Root)
            merge!(doc.trailer, t)
            break
        end
        r = findprev(b"trailer", d, first(r) - 1)
    end
    # Objects that failed while the xref was incomplete are read again when needed.
    empty!(doc.objects)
    haskey(doc.trailer, :Root) || error("Not a readable PDF: no document catalog")
    return doc
end

# ---------------------------------------------------------------------------
# Stream filters (section 7.4)
# ---------------------------------------------------------------------------

"Returns the decoded bytes of a stream."
function decode(doc::Document, stream::Stream)
    filters = getvalue(doc, stream.dict, :Filter)
    params = getvalue(doc, stream.dict, :DecodeParms)
    filters === nothing && return stream.data
    if filters isa Symbol
        filters = Any[filters]
        params = Any[params]
    elseif !(params isa AbstractVector)
        params = fill(params, length(filters))
    end
    data = stream.data
    for (filter, param) in zip(filters, params)
        filter = resolve(doc, filter)
        param = resolve(doc, param)
        if filter === :FlateDecode || filter === :Fl
            data = flate_decode(data)
            param isa Dict && (data = unpredict(doc, data, param))
        elseif filter === :LZWDecode || filter === :LZW
            early = param isa Dict ? getvalue(doc, param, :EarlyChange, 1) : 1
            data = lzw_decode(data, early)
            param isa Dict && (data = unpredict(doc, data, param))
        elseif filter === :ASCIIHexDecode || filter === :AHx
            data = read_hex_string!(Lexer(vcat(UInt8('<'), data), 1))
        elseif filter === :ASCII85Decode || filter === :A85
            data = ascii85_decode(data)
        elseif filter === :RunLengthDecode || filter === :RL
            data = run_length_decode(data)
        else
            error("Unsupported PDF stream filter: $filter")
        end
    end
    return data
end

"""
Decompresses zlib data. Like other PDF readers, it accepts data whose Adler-32
checksum at the end is wrong or missing, by reading the Deflate data inside,
but warns, as the data may also be damaged.
"""
function flate_decode(data::Vector{UInt8})
    try
        return inflate_zlib(data)
    catch err
        (err isa InterruptException || length(data) <= 2) && rethrow()
        out = inflate(data[3:end])  # after the 2-byte zlib header
        @warn "A PDF stream's checksum is wrong or missing, so its text may be damaged"
        return out
    end
end

"Decodes ASCII85 (section 7.4.3): groups of 5 characters from ! to u for 4 bytes, z for 4 zeros."
function ascii85_decode(data::Vector{UInt8})
    out = UInt8[]
    group = UInt64(0)
    k = 0
    for b in data
        b == UInt8('~') && break  # the end marker ~>
        iswhite(b) && continue
        if b == UInt8('z') && k == 0
            append!(out, (0x00, 0x00, 0x00, 0x00))
            continue
        end
        UInt8('!') <= b <= UInt8('u') || error("Damaged ASCII85 data")
        group = 85 * group + (b - UInt8('!'))
        k += 1
        if k == 5
            group > 0xffffffff && error("Damaged ASCII85 data")
            append!(out, reinterpret(UInt8, [hton(UInt32(group))]))
            group, k = UInt64(0), 0
        end
    end
    if k > 1
        # A last group of k characters is padded with u and gives k - 1 bytes.
        for _ in k+1:5
            group = 85 * group + 84
        end
        append!(out, reinterpret(UInt8, [hton(UInt32(group & 0xffffffff))])[1:k-1])
    end
    return out
end

"Decodes RunLength data (section 7.4.5)."
function run_length_decode(data::Vector{UInt8})
    out = UInt8[]
    p = 1
    while p <= length(data)
        n = data[p]
        p += 1
        n == 128 && break  # end of data
        if n < 128
            # The next n + 1 bytes are copied.
            append!(out, view(data, p:min(p + n, length(data))))
            p += n + 1
        elseif p <= length(data)
            # The next byte is repeated 257 - n times.
            append!(out, fill(data[p], 257 - n))
            p += 1
        end
    end
    return out
end

"Decodes LZW data (section 7.4.4), with codes of 9 to 12 bits."
function lzw_decode(data::Vector{UInt8}, early::Integer = 1)
    out = UInt8[]
    table = [[UInt8(i)] for i in 0:255]
    push!(table, UInt8[], UInt8[])  # 256 clears the table, 257 ends the data
    bits = 9
    buffer = 0
    nbits = 0
    previous = UInt8[]
    for b in data
        buffer = ((buffer << 8) | b) & 0xffffff
        nbits += 8
        while nbits >= bits
            code = (buffer >> (nbits - bits)) & ((1 << bits) - 1)
            nbits -= bits
            if code == 256
                resize!(table, 258)
                bits = 9
                previous = UInt8[]
                continue
            end
            code == 257 && return out
            if code < length(table)
                entry = table[code+1]
            elseif !isempty(previous) && code == length(table)
                entry = vcat(previous, previous[1])
            else
                error("Damaged LZW data")
            end
            append!(out, entry)
            isempty(previous) || length(table) < 4096 && push!(table, vcat(previous, entry[1]))
            previous = entry
            # The code length grows one code early when EarlyChange is 1.
            bits = min(12, length(table) + early >= (1 << bits) ? bits + 1 : bits)
        end
    end
    return out
end

"Undoes a TIFF (2) or PNG (10 to 15) predictor, which xref streams often use."
function unpredict(doc::Document, data::Vector{UInt8}, param::Dict{Symbol,Any})
    predictor = getvalue(doc, param, :Predictor, 1)
    predictor == 1 && return data
    colors = getvalue(doc, param, :Colors, 1)
    bits = getvalue(doc, param, :BitsPerComponent, 8)
    columns = getvalue(doc, param, :Columns, 1)
    bpp = max(1, (colors * bits) ÷ 8)          # bytes per pixel
    rowlength = (colors * bits * columns + 7) ÷ 8
    if predictor == 2
        bits == 8 || error("Unsupported TIFF predictor with $bits bits per component")
        out = copy(data)
        for row in 0:(length(out) ÷ rowlength)-1, i in bpp+1:rowlength
            k = row * rowlength + i
            out[k] += out[k-bpp]
        end
        return out
    end
    out = UInt8[]
    previous = zeros(UInt8, rowlength)
    current = zeros(UInt8, rowlength)
    p = 1
    while p + rowlength <= length(data)
        type = data[p]
        for i in 1:rowlength
            raw = data[p+i]
            left = i > bpp ? current[i-bpp] : 0x00
            up = previous[i]
            upleft = i > bpp ? previous[i-bpp] : 0x00
            current[i] = if type == 0
                raw
            elseif type == 1
                raw + left
            elseif type == 2
                raw + up
            elseif type == 3
                raw + UInt8((Int(left) + Int(up)) ÷ 2)
            elseif type == 4
                raw + paeth(left, up, upleft)
            else
                error("Unknown PNG predictor type $type")
            end
        end
        append!(out, current)
        previous, current = current, previous
        p += rowlength + 1
    end
    return out
end

function paeth(a::UInt8, b::UInt8, c::UInt8)
    p = Int(a) + Int(b) - Int(c)
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    return pa <= pb && pa <= pc ? a : pb <= pc ? b : c
end

# ---------------------------------------------------------------------------
# Fonts (section 9.5 to 9.10): what text each code in a string stands for
# and how far it moves the text position
# ---------------------------------------------------------------------------

struct Font
    bytes_per_code::Int                 # 1 for simple fonts, 2 for Identity CMaps
    codespace::Vector{Tuple{Int,UInt32,UInt32}}  # (bytes, low, high) of an embedded CMap
    to_unicode::Dict{UInt32,String}     # from the ToUnicode CMap
    encoding::Vector{String}            # simple fonts: text of codes 0 to 255
    code_to_cid::Dict{UInt32,UInt32}    # composite fonts with an embedded CMap
    widths::Dict{UInt32,Float64}        # width of a code (simple) or CID (composite), in text space units
    default_width::Float64
    vertical::Float64                   # vertical fonts (Identity-V): how far down a glyph moves; else 0
    texts::Dict{UInt32,String}          # cache of code_text
end

# The characters of codes 128 to 159 in WinAnsiEncoding (Windows-1252); the
# rest of WinAnsiEncoding is the same as ISO Latin-1. Unused codes are "".
const WIN_ANSI_128_159 = ["€", "", "‚", "ƒ", "„", "…", "†", "‡", "ˆ", "‰", "Š", "‹", "Œ", "", "Ž", "",
                          "", "‘", "’", "“", "”", "•", "–", "—", "˜", "™", "š", "›", "œ", "", "ž", "Ÿ"]

const WIN_ANSI = String[
    code < 32 ? "" : 128 <= code <= 159 ? WIN_ANSI_128_159[code-127] : string(Char(code))
    for code in 0:255
]

# StandardEncoding, the default for Type 1 fonts (Annex D): ASCII, except for
# its quotes, and these codes above 127; its other codes are unused.
const STANDARD_ABOVE_127 = Dict(
    0xa1 => "¡", 0xa2 => "¢", 0xa3 => "£", 0xa4 => "⁄", 0xa5 => "¥", 0xa6 => "ƒ", 0xa7 => "§",
    0xa8 => "¤", 0xa9 => "'", 0xaa => "“", 0xab => "«", 0xac => "‹", 0xad => "›", 0xae => "fi",
    0xaf => "fl", 0xb1 => "–", 0xb2 => "†", 0xb3 => "‡", 0xb4 => "·", 0xb6 => "¶", 0xb7 => "•",
    0xb8 => "‚", 0xb9 => "„", 0xba => "”", 0xbb => "»", 0xbc => "…", 0xbd => "‰", 0xbf => "¿",
    0xc1 => "`", 0xc2 => "´", 0xc3 => "ˆ", 0xc4 => "˜", 0xc5 => "¯", 0xc6 => "˘", 0xc7 => "˙",
    0xc8 => "¨", 0xca => "˚", 0xcb => "¸", 0xcd => "˝", 0xce => "˛", 0xcf => "ˇ", 0xd0 => "—",
    0xe1 => "Æ", 0xe3 => "ª", 0xe8 => "Ł", 0xe9 => "Ø", 0xea => "Œ", 0xeb => "º", 0xf1 => "æ",
    0xf5 => "ı", 0xf8 => "ł", 0xf9 => "ø", 0xfa => "œ", 0xfb => "ß",
)

const STANDARD = [code == 0x27 ? "’" : code == 0x60 ? "‘" : code < 128 ? WIN_ANSI[code+1] :
                  get(STANDARD_ABOVE_127, code, "") for code in 0:255]

# MacRomanEncoding (Annex D) is ASCII below 128; these are codes 128 to 255,
# with "\0" for unused codes.
const MAC_ROMAN_ABOVE_127 = "ÄÅÇÉÑÖÜáàâäãåçéèêëíìîïñóòôöõúùûü†°¢£§•¶ß®©™´¨\0ÆØ\0±\0\0¥µ\0\0\0\0\0ªº\0æø" *
                            "¿¡¬\0ƒ\0\0«»… ÀÃÕŒœ–—“”‘’÷\0ÿŸ⁄¤‹›ﬁﬂ‡·‚„‰ÂÊÁËÈÍÎÏÌÓÔ\0ÒÚÛÙıˆ˜¯˘˙˚¸˝˛ˇ"

const MAC_ROMAN = [WIN_ANSI[1:128]; [c == '\0' ? "" : string(c) for c in MAC_ROMAN_ABOVE_127]]

# The 14 standard fonts need not list their glyph widths (section 9.6.2.1), so
# these are their widths from Adobe's font metrics (AFM) files, in 1/1000 em,
# for the glyphs named in STANDARD_14_NAMES. Courier's glyphs are all 600 wide;
# the Oblique fonts have the widths of the upright ones. Other glyphs of these
# fonts are taken to be 500 wide.
const STANDARD_14_NAMES = split("""
    space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright
    asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon
    semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p
    q r s t u v w x y z braceleft bar braceright asciitilde quoteright quoteleft""")

const STANDARD_14_WIDTHS = Dict(name => Dict(zip(STANDARD_14_NAMES, parse.(Int, split(widths)))) for (name, widths) in (
    "Helvetica" => """
        278 278 355 556 556 889 667 191 333 333 389 584 278 333 278 278 556 556 556 556 556 556 556
        556 556 556 278 278 584 584 584 556 1015 667 667 722 722 667 611 778 722 278 500 667 556 833
        722 778 667 778 722 667 611 722 667 944 667 667 611 278 278 278 469 556 333 556 556 500 556
        556 278 556 556 222 222 500 222 833 556 556 556 556 333 500 278 556 500 722 500 500 500 334
        260 334 584 222 222""",
    "Helvetica-Bold" => """
        278 333 474 556 556 889 722 238 333 333 389 584 278 333 278 278 556 556 556 556 556 556 556
        556 556 556 333 333 584 584 584 611 975 722 722 722 722 667 611 778 722 278 556 722 611 833
        722 778 667 778 722 667 611 722 667 944 667 667 611 333 278 333 584 556 333 556 611 556 611
        556 333 611 611 278 278 556 278 889 611 611 611 611 389 556 333 611 556 778 556 556 500 389
        280 389 584 278 278""",
    "Times-Roman" => """
        250 333 408 500 500 833 778 180 333 333 500 564 250 333 250 278 500 500 500 500 500 500 500
        500 500 500 278 278 564 564 564 444 921 722 667 667 722 611 556 722 722 333 389 722 611 889
        722 722 556 722 667 556 611 722 722 944 722 722 611 333 278 333 469 500 333 444 500 444 500
        444 333 500 500 278 278 500 278 778 500 500 500 500 333 389 278 500 500 722 500 500 444 480
        200 480 541 333 333""",
    "Times-Bold" => """
        250 333 555 500 500 1000 833 278 333 333 500 570 250 333 250 278 500 500 500 500 500 500 500
        500 500 500 333 333 570 570 570 500 930 722 667 722 722 667 611 778 778 389 500 778 667 944
        722 778 611 778 722 556 667 722 722 1000 722 722 667 333 278 333 581 500 333 500 556 444 556
        444 333 500 556 278 333 556 278 833 556 500 556 556 444 389 333 556 500 722 500 500 444 394
        220 394 520 333 333""",
    "Times-Italic" => """
        250 333 420 500 500 833 778 214 333 333 500 675 250 333 250 278 500 500 500 500 500 500 500
        500 500 500 333 333 675 675 675 500 920 611 611 667 722 611 611 722 722 333 444 667 556 833
        667 722 611 722 611 500 556 722 611 833 611 556 556 389 278 389 422 500 333 500 500 444 500
        444 278 500 500 278 278 444 278 722 500 500 500 500 389 389 278 500 444 667 444 444 389 400
        275 400 541 333 333""",
    "Times-BoldItalic" => """
        250 389 555 500 500 833 778 278 333 333 500 570 250 333 250 278 500 500 500 500 500 500 500
        500 500 500 333 333 570 570 570 500 832 667 667 667 722 667 667 722 778 389 500 667 611 889
        722 722 611 722 667 556 611 722 667 889 667 611 611 333 278 333 570 500 333 500 500 444 500
        444 333 500 556 278 278 500 278 778 556 500 500 500 389 389 278 556 444 667 500 444 389 348
        220 348 570 333 333""",
))

"The AFM widths of a standard 14 font (or a common alias of one, such as Arial), or nothing."
function standard_14_widths(basefont)
    basefont isa Symbol || return nothing
    name = String(basefont)
    occursin('+', name) && (name = split(name, '+'; limit = 2)[2])  # a subset prefix, ABCDEF+
    # Arial,Bold and Arial-BoldMT are both a family and a style.
    family, style = occursin(r"[,-]", name) ? split(name, r"[,-]"; limit = 2) : (name, "")
    family = replace(family, r"(PSMT|MT|PS)$" => "")  # ArialMT, TimesNewRomanPSMT
    bold = occursin("Bold", style)
    italic = occursin("Italic", style) || occursin("Oblique", style)
    if family in ("Helvetica", "Arial")
        return STANDARD_14_WIDTHS[bold ? "Helvetica-Bold" : "Helvetica"]
    elseif family in ("Times", "TimesNewRoman")
        return STANDARD_14_WIDTHS[bold && italic ? "Times-BoldItalic" : bold ? "Times-Bold" :
                                  italic ? "Times-Italic" : "Times-Roman"]
    elseif family in ("Courier", "CourierNew")
        return Dict(n => 600 for n in STANDARD_14_NAMES)
    end
    return nothing
end

# Glyph names used in /Differences arrays, beyond those named after their
# character (such as /A) or written as /uniXXXX or /uXXXX.
const GLYPH_NAMES = Dict(
    "space" => " ", "exclam" => "!", "quotedbl" => "\"", "numbersign" => "#", "dollar" => "\$",
    "percent" => "%", "ampersand" => "&", "quotesingle" => "'", "quoteright" => "’", "quoteleft" => "‘",
    "parenleft" => "(", "parenright" => ")", "asterisk" => "*", "plus" => "+", "comma" => ",",
    "hyphen" => "-", "minus" => "−", "period" => ".", "slash" => "/", "zero" => "0", "one" => "1",
    "two" => "2", "three" => "3", "four" => "4", "five" => "5", "six" => "6", "seven" => "7",
    "eight" => "8", "nine" => "9", "colon" => ":", "semicolon" => ";", "less" => "<", "equal" => "=",
    "greater" => ">", "question" => "?", "at" => "@", "bracketleft" => "[", "backslash" => "\\",
    "bracketright" => "]", "asciicircum" => "^", "underscore" => "_", "grave" => "`",
    "braceleft" => "{", "bar" => "|", "braceright" => "}", "asciitilde" => "~",
    "quotedblleft" => "“", "quotedblright" => "”", "quotesinglbase" => "‚", "quotedblbase" => "„",
    "endash" => "–", "emdash" => "—", "bullet" => "•", "ellipsis" => "…", "section" => "§",
    "paragraph" => "¶", "degree" => "°", "copyright" => "©", "registered" => "®",
    "trademark" => "™", "dagger" => "†", "daggerdbl" => "‡", "nbspace" => " ",
    "fi" => "fi", "fl" => "fl", "ff" => "ff", "ffi" => "ffi", "ffl" => "ffl",
    "AE" => "Æ", "ae" => "æ", "OE" => "Œ", "oe" => "œ", "Oslash" => "Ø", "oslash" => "ø",
    "Lslash" => "Ł", "lslash" => "ł", "germandbls" => "ß", "dotlessi" => "ı", "Eth" => "Ð",
    "eth" => "ð", "Thorn" => "Þ", "thorn" => "þ", "exclamdown" => "¡", "questiondown" => "¿",
    "guillemotleft" => "«", "guillemotright" => "»", "guilsinglleft" => "‹", "guilsinglright" => "›",
    "cent" => "¢", "sterling" => "£", "yen" => "¥", "Euro" => "€", "currency" => "¤",
    "florin" => "ƒ", "perthousand" => "‰", "periodcentered" => "·", "fraction" => "⁄",
    "multiply" => "×", "divide" => "÷", "plusminus" => "±", "logicalnot" => "¬", "mu" => "µ",
    "ordfeminine" => "ª", "ordmasculine" => "º", "onehalf" => "½", "onequarter" => "¼",
    "threequarters" => "¾", "brokenbar" => "¦", "onesuperior" => "¹", "twosuperior" => "²",
    "threesuperior" => "³", "acute" => "´", "circumflex" => "ˆ", "tilde" => "˜", "macron" => "¯",
    "breve" => "˘", "dotaccent" => "˙", "dieresis" => "¨", "ring" => "˚", "cedilla" => "¸",
    "hungarumlaut" => "˝", "ogonek" => "˛", "caron" => "ˇ", "asteriskmath" => "∗", "infinity" => "∞",
    "lessequal" => "≤", "greaterequal" => "≥", "notequal" => "≠", "approxequal" => "≈",
    "partialdiff" => "∂", "summation" => "∑", "product" => "∏", "radical" => "√", "integral" => "∫",
    "element" => "∈", "arrowright" => "→", "arrowleft" => "←", "arrowup" => "↑", "arrowdown" => "↓",
    "prime" => "′", "sigma1" => "ς", "dmacron" => "đ", "dcroat" => "đ", "Dcroat" => "Đ",
    "Ldotaccent" => "Ŀ", "ldotaccent" => "ŀ", "Ldot" => "Ŀ", "ldot" => "ŀ",
)

# Greek letters, as the Adobe Glyph List names them (with ∆, Ω and µ for Delta, Omega and mu).
for (name, char) in zip(split("Alpha Beta Gamma Delta Epsilon Zeta Eta Theta Iota Kappa Lambda Mu Nu Xi " *
                              "Omicron Pi Rho Sigma Tau Upsilon Phi Chi Psi Omega alpha beta gamma delta " *
                              "epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau " *
                              "upsilon phi chi psi omega"),
                        "ΑΒΓ∆ΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλµνξοπρστυφχψω")
    GLYPH_NAMES[name] = string(char)
end

# Accents in glyph names such as /eacute, as combining characters.
const ACCENTS = Dict(
    "acute" => '\u0301', "grave" => '\u0300', "circumflex" => '\u0302', "tilde" => '\u0303',
    "dieresis" => '\u0308', "ring" => '\u030a', "cedilla" => '\u0327', "caron" => '\u030c',
    "macron" => '\u0304', "breve" => '\u0306', "ogonek" => '\u0328', "dotaccent" => '\u0307',
    "hungarumlaut" => '\u030b',
)

"The text of a glyph name (Adobe Glyph List conventions), or \"\" if unknown."
function glyph_text(name::AbstractString)
    base = split(name, '.')[1]  # /a.sc is a small capital a
    haskey(GLYPH_NAMES, base) && return GLYPH_NAMES[base]
    # /f_f_i is the ligature of f, f and i.
    occursin('_', base) && return join(glyph_text(part) for part in split(base, '_'))
    if length(base) == 1 && isascii(base[1]) && isletter(base[1])
        return String(base)
    end
    m = match(r"^([A-Za-z])([a-z]+)$", base)
    if m !== nothing && haskey(ACCENTS, m.captures[2])
        # A letter and its accent, joined into one character where Unicode has one.
        return Base.Unicode.normalize(m.captures[1] * ACCENTS[m.captures[2]], :NFC)
    end
    m = match(r"^uni((?:[0-9A-F]{4})+)$", base)
    if m !== nothing
        hex = m.captures[1]
        units = UInt16[parse(UInt16, hex[i:i+3], base = 16) for i in 1:4:length(hex)]
        return transcode(String, units)
    end
    m = match(r"^u([0-9A-F]{4,6})$", base)
    if m !== nothing
        c = parse(UInt32, m.captures[1], base = 16)
        return isvalid(Char, c) ? string(Char(c)) : ""
    end
    return ""
end

"Decodes UTF-16BE bytes, the encoding of text in ToUnicode CMaps."
function utf16be(bytes::AbstractVector{UInt8})
    length(bytes) == 1 && return string(Char(bytes[1]))
    units = UInt16[(UInt16(bytes[i]) << 8) | bytes[i+1] for i in 1:2:length(bytes)-1]
    return transcode(String, units)
end

bytes_to_uint(bytes::AbstractVector{UInt8}) = foldl((v, b) -> (v << 8) | b, bytes; init = UInt32(0))

"""
Reads a CMap (section 9.7.5 and 9.10.3): its codespace ranges, the text of
each code (bfchar and bfrange) and the CID of each code (cidchar and cidrange).
"""
function read_cmap(data::Vector{UInt8})
    codespace = Tuple{Int,UInt32,UInt32}[]
    to_unicode = Dict{UInt32,String}()
    to_cid = Dict{UInt32,UInt32}()
    lx = Lexer(data, 1)
    operands = Any[]
    while true
        t = read_object(lx; refs = false)
        t === EOF && break
        if !(t isa Keyword)
            push!(operands, t)
            continue
        end
        empty!(operands)
        section = t.word
        section in ("begincodespacerange", "beginbfchar", "beginbfrange", "begincidchar", "begincidrange") || continue
        stop = Keyword("end" * section[6:end])
        items = Any[]
        while (x = read_object(lx; refs = false)) != stop && x !== EOF
            push!(items, x)
        end
        if section == "begincodespacerange"
            for i in 1:2:length(items)-1
                low, high = items[i], items[i+1]
                (low isa Vector{UInt8} && high isa Vector{UInt8}) || continue
                push!(codespace, (length(low), bytes_to_uint(low), bytes_to_uint(high)))
            end
        elseif section == "beginbfchar"
            for i in 1:2:length(items)-1
                code, text = items[i], items[i+1]
                code isa Vector{UInt8} || continue
                to_unicode[bytes_to_uint(code)] =
                    text isa Vector{UInt8} ? utf16be(text) : text isa Symbol ? glyph_text(string(text)) : ""
            end
        elseif section == "beginbfrange"
            for i in 1:3:length(items)-2
                low, high, text = items[i], items[i+1], items[i+2]
                (low isa Vector{UInt8} && high isa Vector{UInt8}) || continue
                lo, hi = bytes_to_uint(low), bytes_to_uint(high)
                hi - lo > 0xffff && continue  # not a real mapping
                for (k, code) in enumerate(lo:hi)
                    if text isa Vector{UInt8} && !isempty(text)
                        # The last byte counts up from the first code's text.
                        t = copy(text)
                        t[end] += UInt8((code - lo) % 256)
                        to_unicode[code] = utf16be(t)
                    elseif text isa Vector && k <= length(text) && text[k] isa Vector{UInt8}
                        to_unicode[code] = utf16be(text[k])
                    end
                end
            end
        elseif section == "begincidchar"
            for i in 1:2:length(items)-1
                code, cid = items[i], items[i+1]
                (code isa Vector{UInt8} && cid isa Int) && (to_cid[bytes_to_uint(code)] = UInt32(cid))
            end
        else  # begincidrange
            for i in 1:3:length(items)-2
                low, high, cid = items[i], items[i+1], items[i+2]
                (low isa Vector{UInt8} && high isa Vector{UInt8} && cid isa Int) || continue
                lo, hi = bytes_to_uint(low), bytes_to_uint(high)
                hi - lo > 0xffff && continue
                for code in lo:hi
                    to_cid[code] = UInt32(cid + (code - lo))
                end
            end
        end
    end
    return codespace, to_unicode, to_cid
end

"Reads a font dictionary into a Font."
function load_font(doc::Document, font::Dict{Symbol,Any})
    subtype = getvalue(doc, font, :Subtype)
    to_unicode = Dict{UInt32,String}()
    tu = getvalue(doc, font, :ToUnicode)
    if tu isa Stream
        try
            to_unicode = read_cmap(decode(doc, tu))[2]
        catch err
            err isa InterruptException && rethrow()
            @warn "Ignoring a PDF font's ToUnicode CMap, which cannot be read" exception = err
        end
    end
    widths = Dict{UInt32,Float64}()

    if subtype === :Type0
        # A composite font: codes select CIDs through its CMap.
        descendant = resolve(doc, getvalue(doc, font, :DescendantFonts, Any[nothing])[1])
        descendant isa Dict || (descendant = Dict{Symbol,Any}())
        encoding = getvalue(doc, font, :Encoding)
        codespace = Tuple{Int,UInt32,UInt32}[]
        code_to_cid = Dict{UInt32,UInt32}()
        if encoding isa Stream
            try
                codespace, _, code_to_cid = read_cmap(decode(doc, encoding))
            catch err
                err isa InterruptException && rethrow()
                @warn "Reading a PDF font's CMap as Identity-H, as it cannot be read" exception = err
            end
        end
        # /W lists widths as `first [w1 w2 ...]` or `first last w`.
        w = getvalue(doc, descendant, :W, Any[])
        i = 1
        while i < length(w)
            start = resolve(doc, w[i])
            second = resolve(doc, w[i+1])
            start isa Int && start >= 0 || break
            if second isa AbstractVector
                for (k, width) in enumerate(second)
                    widths[UInt32(start + k - 1)] = number(resolve(doc, width)) / 1000
                end
                i += 2
            elseif i + 2 <= length(w) && second isa Int
                width = number(resolve(doc, w[i+2])) / 1000
                for cid in max(start, 0):min(second, 0xffff)  # CIDs are at most 65535
                    widths[UInt32(cid)] = width
                end
                i += 3
            else
                break
            end
        end
        default_width = getvalue(doc, descendant, :DW, 1000) / 1000
        # Vertical writing (section 9.7.4.3): each glyph moves the text down by
        # the second number of /DW2 (glyph-specific /W2 values are not read).
        vertical = encoding === Symbol("Identity-V") ||
                   (encoding isa Stream && getvalue(doc, encoding.dict, :WMode, 0) == 1)
        dw2 = getvalue(doc, descendant, :DW2, Any[880, -1000])
        advance = vertical ? -number(resolve(doc, dw2[end])) / 1000 : 0.0
        return Font(2, codespace, to_unicode, String[], code_to_cid, widths, default_width, advance,
                    Dict{UInt32,String}())
    end

    # A simple font: one byte per code.
    encoding = getvalue(doc, font, :Encoding)
    base = encoding isa Dict ? getvalue(doc, encoding, :BaseEncoding) : encoding
    # Without an encoding, a Type 1 font uses its own, usually StandardEncoding.
    standard = base === :StandardEncoding || (base === nothing && subtype in (:Type1, :MMType1))
    table = copy(standard ? STANDARD : base === :MacRomanEncoding ? MAC_ROMAN : WIN_ANSI)
    if base === nothing && subtype in (:Type1, :MMType1)
        # An embedded Type 1 font program starts with its encoding in plain
        # text, as `dup 65 /A put` (TeX fonts, for example, use their own).
        descriptor = getvalue(doc, font, :FontDescriptor)
        program = descriptor isa Dict ? getvalue(doc, descriptor, :FontFile) : nothing
        if program isa Stream
            data = try
                decode(doc, program)
            catch
                UInt8[]
            end
            r = findfirst(b"eexec", data)
            header = data[1:(r === nothing ? length(data) : first(r) - 1)]
            header = String(map(Char, header))  # read as Latin-1, as it need not be UTF-8
            for m in eachmatch(r"dup\s+(\d+)\s*/([^\s/\[\]]+)\s+put", header)
                code = parse(Int, m.captures[1])
                0 <= code <= 255 && (table[code+1] = glyph_text(m.captures[2]))
            end
        end
    end
    # The glyph names of codes 32 to 126, for the widths of the standard 14 fonts.
    names = Dict{Int,String}(code => STANDARD_14_NAMES[code-31] for code in 32:126)
    if standard
        names[0x27], names[0x60] = "quoteright", "quoteleft"
    end
    if encoding isa Dict
        code = 0
        for item in getvalue(doc, encoding, :Differences, Any[])
            item = resolve(doc, item)
            if item isa Int
                code = item
            elseif item isa Symbol
                if 0 <= code <= 255
                    table[code+1] = glyph_text(string(item))
                    names[code] = string(item)
                end
                code += 1
            end
        end
    end
    # Type 3 glyphs are measured with the font's matrix; others in 1/1000 em.
    scale = 0.001
    if subtype === :Type3
        matrix = getvalue(doc, font, :FontMatrix, Any[0.001])
        scale = number(resolve(doc, matrix[1]))
    end
    firstchar = getvalue(doc, font, :FirstChar, 0)
    for (k, width) in enumerate(getvalue(doc, font, :Widths, Any[]))
        widths[UInt32(firstchar + k - 1)] = number(resolve(doc, width)) * scale
    end
    descriptor = getvalue(doc, font, :FontDescriptor, Dict{Symbol,Any}())
    missing_width = descriptor isa Dict ? getvalue(doc, descriptor, :MissingWidth, 0) : 0
    default_width = missing_width * scale
    if isempty(widths) && subtype !== :Type3
        # A standard 14 font without /Widths; for other fonts, a guess.
        afm = standard_14_widths(getvalue(doc, font, :BaseFont))
        for (code, name) in names
            afm !== nothing && haskey(afm, name) && (widths[UInt32(code)] = afm[name] / 1000)
        end
        default_width = 0.5
    end
    return Font(1, Tuple{Int,UInt32,UInt32}[], to_unicode, table, Dict{UInt32,UInt32}(), widths,
                default_width, 0.0, Dict{UInt32,String}())
end

"Splits the bytes of a string into character codes, each with its length in bytes."
function codes(font::Font, s::Vector{UInt8})
    out = Tuple{UInt32,Int}[]
    i = 1
    n = length(s)
    while i <= n
        len = font.bytes_per_code
        if !isempty(font.codespace)
            # The shortest codespace range that holds the next bytes.
            len = 0
            for k in 1:4
                i + k - 1 > n && break
                v = bytes_to_uint(view(s, i:i+k-1))
                if any(r -> r[1] == k && r[2] <= v <= r[3], font.codespace)
                    len = k
                    break
                end
            end
            len == 0 && (len = min(font.bytes_per_code, n - i + 1))
        end
        len = min(len, n - i + 1)
        push!(out, (bytes_to_uint(view(s, i:i+len-1)), len))
        i += len
    end
    return out
end

"The text of a character code, from the ToUnicode CMap or else the encoding."
function code_text(font::Font, code::UInt32)
    get!(font.texts, code) do
        text = get(font.to_unicode, code, nothing)
        if text === nothing
            text = font.bytes_per_code == 1 && code <= 255 ? font.encoding[code+1] : ""
        end
        clean(text)
    end
end

# Ligature characters, which some fonts map glyphs such as "fi" to, are
# replaced by the letters they join.
const LIGATURES = Dict('ﬀ' => "ff", 'ﬁ' => "fi", 'ﬂ' => "fl", 'ﬃ' => "ffi", 'ﬄ' => "ffl", 'ﬅ' => "st", 'ﬆ' => "st")

"Replaces ligatures, turns tabs and line breaks into spaces and removes other control characters."
function clean(text::String)
    io = IOBuffer()
    for c in text
        if haskey(LIGATURES, c)
            print(io, LIGATURES[c])
        elseif c == '\t' || c == '\n' || c == '\r'
            print(io, ' ')
        elseif !iscntrl(c)
            print(io, c)
        end
    end
    return String(take!(io))
end

function code_width(font::Font, code::UInt32)
    key = font.bytes_per_code == 1 ? code : get(font.code_to_cid, code, code)
    return get(font.widths, key, font.default_width)
end

# ---------------------------------------------------------------------------
# Content streams (section 8 and 9): where each glyph is drawn
# ---------------------------------------------------------------------------

"One glyph of text: its text, where its baseline starts, its width and its font size."
struct Glyph
    text::String
    x::Float64
    y::Float64
    width::Float64
    size::Float64
    horizontal::Bool  # whether it is written left to right on a horizontal baseline
end

# Matrices [a b c d e f] stand for [a b 0; c d 0; e f 1] (section 8.3.3).
const Matrix6 = NTuple{6,Float64}
const IDENTITY = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)

multiply(m::Matrix6, n::Matrix6) = (
    m[1] * n[1] + m[2] * n[3], m[1] * n[2] + m[2] * n[4],
    m[3] * n[1] + m[4] * n[3], m[3] * n[2] + m[4] * n[4],
    m[5] * n[1] + m[6] * n[3] + n[5], m[5] * n[2] + m[6] * n[4] + n[6],
)

translate(m::Matrix6, tx::Float64, ty::Float64) =
    (m[1], m[2], m[3], m[4], tx * m[1] + ty * m[3] + m[5], tx * m[2] + ty * m[4] + m[6])

"The parts of the graphics state that q and Q save and restore and that place text."
mutable struct GraphicsState
    ctm::Matrix6
    font::Union{Font,Nothing}
    size::Float64       # Tf
    charspace::Float64  # Tc
    wordspace::Float64  # Tw
    hscale::Float64     # Tz / 100
    leading::Float64    # TL
    rise::Float64       # Ts
end

GraphicsState(ctm::Matrix6) = GraphicsState(ctm, nothing, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
Base.copy(g::GraphicsState) =
    GraphicsState(g.ctm, g.font, g.size, g.charspace, g.wordspace, g.hscale, g.leading, g.rise)

mutable struct TextState
    tm::Matrix6   # text matrix
    tlm::Matrix6  # text line matrix
end

number(x) = x isa Real ? Float64(x) : 0.0

"Draws the glyphs of string `s` with the current font, moving the text matrix past them."
function show_text!(glyphs::Vector{Glyph}, gs::GraphicsState, ts::TextState, s::Vector{UInt8})
    font = gs.font
    font === nothing && return
    for (code, len) in codes(font, s)
        w0 = code_width(font, code)
        # The text rendering matrix (section 9.4.4) places the glyph on the page.
        trm = multiply((gs.size * gs.hscale, 0.0, 0.0, gs.size, 0.0, gs.rise), multiply(ts.tm, gs.ctm))
        horizontal = font.vertical == 0 && trm[1] > 0 && abs(trm[2]) <= 0.05 * trm[1]
        push!(glyphs, Glyph(code_text(font, code), trm[5], trm[6],
                            font.vertical == 0 ? w0 * hypot(trm[1], trm[2]) : font.vertical * hypot(trm[3], trm[4]),
                            hypot(trm[3], trm[4]), horizontal))
        # Word spacing applies to the single-byte code 32 (section 9.3.3).
        spacing = gs.charspace + (len == 1 && code == 32 ? gs.wordspace : 0.0)
        if font.vertical == 0
            ts.tm = translate(ts.tm, (w0 * gs.size + spacing) * gs.hscale, 0.0)
        else
            ts.tm = translate(ts.tm, 0.0, spacing - font.vertical * gs.size)
        end
    end
end

"Moves to the start of the next line, offset by (tx, ty) from the start of the current one."
function next_line!(ts::TextState, tx::Float64, ty::Float64)
    ts.tlm = translate(ts.tlm, tx, ty)
    ts.tm = ts.tlm
end

function restore!(gs::GraphicsState, saved::GraphicsState)
    gs.ctm, gs.font, gs.size, gs.charspace = saved.ctm, saved.font, saved.size, saved.charspace
    gs.wordspace, gs.hscale, gs.leading, gs.rise = saved.wordspace, saved.hscale, saved.leading, saved.rise
    return gs
end

"""
Adds the glyphs drawn by a content stream to `glyphs`. `forms` holds the form
XObjects being drawn, as a form that draws itself (directly or through other
forms) is drawn only once.
"""
function run_content!(glyphs::Vector{Glyph}, doc::Document, content::Vector{UInt8},
                      resources, gs::GraphicsState, fonts::IdDict{Any,Union{Font,Nothing}},
                      forms::Base.IdSet{Any} = Base.IdSet{Any}())
    length(forms) > 20 && return glyphs  # form XObjects nested too deeply
    resources = resolve(doc, resources)
    resources isa Dict || (resources = Dict{Symbol,Any}())
    font_dict = getvalue(doc, resources, :Font, Dict{Symbol,Any}())
    xobjects = getvalue(doc, resources, :XObject, Dict{Symbol,Any}())
    saved = GraphicsState[]
    ts = TextState(IDENTITY, IDENTITY)
    operands = Any[]
    lx = Lexer(content, 1)
    while true
        t = read_object(lx; refs = false)
        t === EOF && break
        if !(t isa Keyword)
            push!(operands, t)
            continue
        end
        op = t.word
        n = length(operands)
        last = n >= 1 ? operands[n] : nothing
        if op == "q"
            push!(saved, copy(gs))
        elseif op == "Q"
            isempty(saved) || restore!(gs, pop!(saved))
        elseif op == "cm" && n >= 6
            gs.ctm = multiply(ntuple(i -> number(operands[n-6+i]), 6), gs.ctm)
        elseif op == "BT"
            ts.tm = ts.tlm = IDENTITY
        elseif op == "Tf" && n >= 2
            gs.size = number(last)
            dict = font_dict isa Dict ? resolve(doc, get(font_dict, operands[n-1], nothing)) : nothing
            # A font that cannot be read is skipped (and remembered as nothing).
            gs.font = dict isa Dict ? get!(fonts, dict) do
                try
                    load_font(doc, dict)
                catch err
                    err isa InterruptException && rethrow()
                    @warn "Skipping a PDF font that cannot be read" exception = err
                    nothing
                end
            end : nothing
        elseif op == "Tc" && n >= 1
            gs.charspace = number(last)
        elseif op == "Tw" && n >= 1
            gs.wordspace = number(last)
        elseif op == "Tz" && n >= 1
            gs.hscale = number(last) / 100
        elseif op == "TL" && n >= 1
            gs.leading = number(last)
        elseif op == "Ts" && n >= 1
            gs.rise = number(last)
        elseif op == "Td" && n >= 2
            next_line!(ts, number(operands[n-1]), number(last))
        elseif op == "TD" && n >= 2
            gs.leading = -number(last)
            next_line!(ts, number(operands[n-1]), number(last))
        elseif op == "Tm" && n >= 6
            ts.tm = ts.tlm = ntuple(i -> number(operands[n-6+i]), 6)
        elseif op == "T*"
            next_line!(ts, 0.0, -gs.leading)
        elseif op == "Tj" && last isa Vector{UInt8}
            show_text!(glyphs, gs, ts, last)
        elseif op == "'" && last isa Vector{UInt8}
            next_line!(ts, 0.0, -gs.leading)
            show_text!(glyphs, gs, ts, last)
        elseif op == "\"" && n >= 3 && last isa Vector{UInt8}
            gs.wordspace = number(operands[n-2])
            gs.charspace = number(operands[n-1])
            next_line!(ts, 0.0, -gs.leading)
            show_text!(glyphs, gs, ts, last)
        elseif op == "TJ" && last isa Vector{Any}
            for item in last
                if item isa Vector{UInt8}
                    show_text!(glyphs, gs, ts, item)
                elseif item isa Real
                    # A number moves the next glyph left by thousandths of the font size.
                    ts.tm = gs.font !== nothing && gs.font.vertical != 0 ?
                        translate(ts.tm, 0.0, -item / 1000 * gs.size) :
                        translate(ts.tm, -item / 1000 * gs.size * gs.hscale, 0.0)
                end
            end
        elseif op == "Do" && last isa Symbol && xobjects isa Dict
            form = resolve(doc, get(xobjects, last, nothing))
            if form isa Stream && getvalue(doc, form.dict, :Subtype) === :Form && !(form in forms)
                inner = copy(gs)
                matrix = getvalue(doc, form.dict, :Matrix, Any[1, 0, 0, 1, 0, 0])
                (matrix isa AbstractVector && length(matrix) == 6) || (matrix = Any[1, 0, 0, 1, 0, 0])
                inner.ctm = multiply(ntuple(i -> number(resolve(doc, matrix[i])), 6), gs.ctm)
                data = try
                    decode(doc, form)
                catch err
                    err isa InterruptException && rethrow()
                    @warn "Skipping a PDF form XObject that cannot be read" exception = err
                    nothing
                end
                data === nothing && (empty!(operands); continue)
                push!(forms, form)
                try
                    run_content!(glyphs, doc, data,
                                 getvalue(doc, form.dict, :Resources, resources), inner, fonts, forms)
                finally
                    delete!(forms, form)
                end
            end
        elseif op == "BI"
            skip_inline_image!(lx)
        end
        empty!(operands)
    end
    return glyphs
end

"Skips an inline image (BI ... ID data EI), whose data is not PDF syntax."
function skip_inline_image!(lx::Lexer)
    while (t = read_object(lx; refs = false)) != Keyword("ID")
        t === EOF && return
    end
    d, n = lx.data, length(lx.data)
    p = lx.pos + 1  # one whitespace byte follows ID
    while p + 1 <= n
        if d[p] == UInt8('E') && d[p+1] == UInt8('I') && iswhite(d[p-1]) && (p + 2 > n || iswhite(d[p+2]))
            lx.pos = p + 2
            return
        end
        p += 1
    end
    lx.pos = n + 1
end

"""
The page dictionaries in order, each with its resources and the matrix that
places it upright with its bottom left corner at (0, 0), from its /MediaBox
and /Rotate (section 7.7.3.4). All three can be inherited from the page tree.
"""
function pages(doc::Document)
    out = Tuple{Dict{Symbol,Any},Any,Matrix6}[]
    catalog = resolve(doc, doc.trailer[:Root])
    catalog isa Dict || error("Not a readable PDF: no document catalog")
    seen = Base.IdSet{Any}()
    # A stack rather than recursion, as page trees can be deep.
    stack = Any[(getvalue(doc, catalog, :Pages), nothing, nothing, 0)]
    while !isempty(stack)
        node, resources, box, rotate = pop!(stack)
        node = resolve(doc, node)
        (node isa Dict && !(node in seen)) || continue  # skips cycles in the page tree
        push!(seen, node)
        resources = get(node, :Resources, resources)
        box = get(node, :MediaBox, box)
        rotate = get(node, :Rotate, rotate)
        kids = getvalue(doc, node, :Kids)
        if kids isa AbstractVector && getvalue(doc, node, :Type) !== :Page
            for kid in Iterators.reverse(kids)
                push!(stack, (kid, resources, box, rotate))
            end
        else
            push!(out, (node, resources, page_matrix(doc, box, rotate)))
        end
    end
    if isempty(out)
        # The page tree is damaged (or cut off): look for the pages themselves.
        for num in sort!(collect(keys(doc.xref)))
            page = get_object(doc, num)
            if page isa Dict && get(page, :Type, nothing) === :Page
                push!(out, (page, get(page, :Resources, nothing),
                            page_matrix(doc, get(page, :MediaBox, nothing), get(page, :Rotate, 0))))
            end
        end
        isempty(out) && error("No pages found: the PDF is damaged or cut off")
    end
    return out
end

function page_matrix(doc::Document, box, rotate)
    box = resolve(doc, box)
    x0, y0, x1, y1 = box isa AbstractVector && length(box) == 4 ?
        [number(resolve(doc, v)) for v in box] : [0.0, 0.0, 612.0, 792.0]
    x0, x1 = minmax(x0, x1)
    y0, y1 = minmax(y0, y1)
    angle = mod(round(number(resolve(doc, rotate))), 360.0)  # clockwise; a Float, as a damaged value can be huge
    angle == 90 && return (0.0, -1.0, 1.0, 0.0, -y0, x1)
    angle == 180 && return (-1.0, 0.0, 0.0, -1.0, x1, y1)
    angle == 270 && return (0.0, 1.0, -1.0, 0.0, y1, -x0)
    return (1.0, 0.0, 0.0, 1.0, -x0, -y0)
end

"The glyphs of a page, in the order they are drawn."
function page_glyphs(doc::Document, page::Dict{Symbol,Any}, resources, matrix::Matrix6,
                     fonts::IdDict{Any,Union{Font,Nothing}})
    contents = getvalue(doc, page, :Contents)
    streams = contents isa AbstractVector ? [resolve(doc, c) for c in contents] :
              haskey(page, :Contents) ? [contents] : []
    content = UInt8[]
    for s in streams
        if !(s isa Stream)
            s === nothing || continue
            @warn "A PDF page's content stream is missing (the PDF may be damaged)"
            continue
        end
        data = try
            decode(doc, s)
        catch err
            err isa InterruptException && rethrow()
            # One damaged stream loses only its own text.
            @warn "Skipping a PDF content stream that cannot be read" exception = err
            continue
        end
        append!(content, data)
        push!(content, 0x0a)  # content streams split at a token boundary
    end
    glyphs = Glyph[]
    try
        run_content!(glyphs, doc, content, resources, GraphicsState(matrix), fonts)
    catch err
        err isa InterruptException && rethrow()
        # Damaged content loses the rest of its page, not the whole document.
        @warn "Stopped reading a PDF page's content early" exception = err
    end
    return glyphs
end

# ---------------------------------------------------------------------------
# Words and lines
# ---------------------------------------------------------------------------

"A word, or other text without spaces, and where it starts and ends on the page."
struct Word
    text::String
    x::Float64      # left edge, in points from the left of the page
    right::Float64  # right edge (for text that is not horizontal, the x of its last glyph)
end

"A line of text: the baseline's height from the bottom of the page and its words, left to right."
struct Line
    y::Float64
    words::Vector{Word}
end

"The text of a line, with one space between words."
text(line::Line) = join((w.text for w in line.words), " ")

"""
Groups glyphs into lines and words. A glyph is on a line when its baseline is
within 40% of the smaller of its font size and that of the line's first
(highest) glyph, and at least within 0.4 points. A new word starts
after a space, or where the gap after the last glyph is more than 15% of the
font size. A glyph drawn again at almost the same place (to look bold) is
read once. Text that is not horizontal, such as a diagonal watermark or
vertical writing, is not mixed into those lines: each run of it, in the order
it is drawn, is a line of its own.
"""
function lines(glyphs::Vector{Glyph})
    horizontal = filter(g -> g.horizontal, glyphs)
    order = sortperm([g.y for g in horizontal]; rev = true)
    groups = Vector{Vector{Glyph}}()
    for i in order
        g = horizontal[i]
        if isempty(groups) || abs(groups[end][1].y - g.y) > 0.4 * max(min(groups[end][1].size, g.size), 1.0)
            push!(groups, Glyph[])
        end
        push!(groups[end], g)
    end
    out = Line[]
    for group in groups
        sort!(group; by = g -> g.x)
        words = Word[]
        buffer = IOBuffer()
        start = right = -Inf
        kept = Glyph[]
        for g in group
            # Skip a copy of one of the last few glyphs, drawn within 30% of its width and size.
            any(h -> abs(h.x - g.x) < 0.3 * max(h.width, 0.1 * h.size) && abs(h.y - g.y) < 0.3 * h.size &&
                     h.text == g.text, @view kept[max(1, end - 3):end]) && continue
            push!(kept, g)
            # A glyph with no known text ("") keeps its place in the word.
            space = !isempty(g.text) && all(isspace, g.text)
            if space || g.x - right > 0.15 * g.size
                # End the word so far.
                position(buffer) > 0 && push!(words, Word(String(take!(buffer)), start, right))
            end
            if !space && !isempty(g.text)
                position(buffer) == 0 && (start = g.x)
                if occursin(' ', g.text)
                    # Text with a space inside (from a ToUnicode CMap) is two words.
                    for (k, part) in enumerate(split(g.text, ' '))
                        if k > 1 && position(buffer) > 0
                            push!(words, Word(String(take!(buffer)), start, g.x + g.width))
                            start = g.x
                        end
                        print(buffer, part)
                    end
                else
                    print(buffer, g.text)
                end
            end
            right = max(right, g.x + g.width)
        end
        position(buffer) > 0 && push!(words, Word(String(take!(buffer)), start, right))
        isempty(words) || push!(out, Line(group[1].y, words))
    end
    # Runs of glyphs that are not horizontal, placed among the lines by where they start.
    if length(horizontal) < length(glyphs)
        run = Glyph[]
        for (i, g) in enumerate(glyphs)
            g.horizontal || push!(run, g)
            if !isempty(run) && (i == length(glyphs) || glyphs[i+1].horizontal)
                words = run_words(run)
                isempty(words) || push!(out, Line(run[1].y, words))
                run = Glyph[]
            end
        end
        sort!(out; by = line -> line.y, rev = true)
    end
    return out
end

"""
The words of a run of glyphs in the order drawn, in any direction. A new word
starts after a space or where the gap from the end of the last glyph is more
than 15% of the font size. Words are placed at their first and last glyphs.
"""
function run_words(run::Vector{Glyph})
    words = Word[]
    buffer = IOBuffer()
    first = run[1]
    for (k, g) in enumerate(run)
        space = !isempty(g.text) && all(isspace, g.text)
        gap = k == 1 ? 0.0 : hypot(g.x - run[k-1].x, g.y - run[k-1].y) - run[k-1].width
        if (space || gap > 0.15 * g.size) && position(buffer) > 0
            push!(words, Word(String(take!(buffer)), first.x, run[k-1].x))
        end
        position(buffer) == 0 && (first = g)
        space || print(buffer, replace(g.text, ' ' => ""))
    end
    position(buffer) > 0 && push!(words, Word(String(take!(buffer)), first.x, run[end].x))
    return words
end

"""
    read_lines(pdf) -> Vector{Vector{Line}}

Reads the text of every page of a PDF, given as its bytes or as a path to it,
as lines from the top of the page to the bottom, each a list of words from
left to right with their positions, in points from the bottom left corner of
the page's /MediaBox (after the page's /Rotate). Text that is not horizontal,
such as a diagonal watermark, is on lines of its own.
"""
read_lines(path::AbstractString) = read_lines(read(path))

function read_lines(data::Vector{UInt8})
    doc = Document(data)
    fonts = IdDict{Any,Union{Font,Nothing}}()
    return [lines(page_glyphs(doc, page, resources, matrix, fonts)) for (page, resources, matrix) in pages(doc)]
end

end # module
