"""
    ZipReader

Reads the files in a .zip archive in pure Julia, decompressing them with the
pure-Julia Inflate package and checking each one against its CRC-32.

It reads files that are stored or compressed with Deflate, which is what zip
tools use by default, including ZIP64 archives (for files over 4 GB or more
than 65,535 files). It does not read encrypted or split (multi-disk) archives.

Citations:
  Code generated by Claude Code, Anthropic, September 24, 2026, https://claude.ai/code/session_019awDnsGJAcXbzPNQg6VhqU.
"""
module ZipReader

using Inflate

# The CRC-32 of zip files (the one in ISO 3309, reflected polynomial 0xEDB88320).
const CRC_TABLE = let
    table = Vector{UInt32}(undef, 256)
    for n in 0:255
        c = UInt32(n)
        for _ in 1:8
            c = isodd(c) ? 0xedb88320 ⊻ (c >> 1) : c >> 1
        end
        table[n+1] = c
    end
    table
end

function crc32(data::AbstractVector{UInt8})
    c = 0xffffffff
    for b in data
        c = CRC_TABLE[((c ⊻ b) & 0xff) + 1] ⊻ (c >> 8)
    end
    return c ⊻ 0xffffffff
end

# Zip files store numbers little-endian.
le16(d::Vector{UInt8}, i::Int) = Int(d[i]) | Int(d[i+1]) << 8
le32(d::Vector{UInt8}, i::Int) = Int(d[i]) | Int(d[i+1]) << 8 | Int(d[i+2]) << 16 | Int(d[i+3]) << 24
le64(d::Vector{UInt8}, i::Int) = le32(d, i) | le32(d, i + 4) << 32

# Code page 437, the character set of zip file names without flag bit 11, from 128 to 255.
const CP437 = collect("ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀" *
                      "αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■\u00a0")

"""
File names are UTF-8 when flag bit 11 is set. Without it they should be in
code page 437, but many tools write UTF-8 anyway, so names that are valid
UTF-8 are read as UTF-8 and others as code page 437.
"""
function file_name(bytes::Vector{UInt8})
    name = String(copy(bytes))
    isvalid(name) && return name
    return String([b < 0x80 ? Char(b) : CP437[b-0x7f] for b in bytes])
end

"""
Finds the end of central directory record: 22 bytes, then a comment of up to
65,535 bytes that runs to the end of the file. Returns its index, or 0.
"""
function find_end_record(data::Vector{UInt8})
    n = length(data)
    best, best_end, fallback = 0, 0, 0
    for i in n-21:-1:max(1, n - 65556)
        if data[i] == 0x50 && data[i+1] == 0x4b && data[i+2] == 0x05 && data[i+3] == 0x06
            # A comment could itself contain the signature, so the record whose
            # comment reaches furthest without passing the end of the file is
            # used (on a tie, the earlier one, whose comment holds the other).
            record_end = i + 21 + le16(data, i + 20)
            record_end <= n && record_end >= best_end && ((best, best_end) = (i, record_end))
            fallback == 0 && (fallback = i)
        end
    end
    return best == 0 ? fallback : best
end

"""
    read_zip(data; keep = path -> true) -> Vector{Pair{String,Vector{UInt8}}}

Returns the path and contents of every file in a zip archive, given as its
bytes, in the order the archive lists them. Folders, and files whose path
`keep` returns false for, are left out (and not decompressed).

The file list is read from the central directory at the end of the archive,
because the headers before each file may leave out its size.
"""
function read_zip(data::Vector{UInt8}; keep = path -> true)
    n = length(data)
    eocd = find_end_record(data)
    eocd == 0 && error("Not a zip file, or the zip file is cut off (it has no end of central directory record)")
    disk, directory_disk = le16(data, eocd + 4), le16(data, eocd + 6)
    count, size, offset = le16(data, eocd + 10), le32(data, eocd + 12), le32(data, eocd + 16)
    directory_end = eocd  # the central directory ends where the next record starts
    zip64 = false
    locator = eocd - 20
    if locator >= 1 && le32(data, locator) == 0x07064b50
        # A ZIP64 archive: its ZIP64 end record, which the locator points to,
        # holds the numbers that may not fit in the end record.
        record = le64(data, locator + 8) + 1
        if !(1 <= record <= n - 55 && le32(data, record) == 0x06064b50)
            # The locator's offset does not count anything before the archive
            # (such as a self-extracting program), but the record is normally
            # the 56 bytes just before the locator.
            record = locator - 56
        end
        (1 <= record <= n - 55 && le32(data, record) == 0x06064b50) || error("Damaged zip file: bad ZIP64 end record")
        disk, directory_disk = le32(data, record + 16), le32(data, record + 20)
        count, size, offset = le64(data, record + 32), le64(data, record + 40), le64(data, record + 48)
        directory_end = record
        zip64 = true
    end
    (disk == 0 && directory_disk == 0) || error("Split (multi-disk) zip files are not supported")
    # Where the central directory really starts, less where the archive says it
    # starts, is the length of anything before the archive (such as a
    # self-extracting program), which moves every offset.
    start = directory_end - size
    start >= 1 || error("Damaged zip file: bad central directory")
    shift = start - (offset + 1)

    files = Pair{String,Vector{UInt8}}[]
    p = start
    entries = 0
    # The entries are read up to the end of the central directory rather than
    # trusting the count, which old tools wrote modulo 65,536 without ZIP64.
    while p < directory_end
        p + 3 <= n && le32(data, p) == 0x05054b50 && break  # an (old) digital signature record
        (p + 45 <= n && le32(data, p) == 0x02014b50) || error("Damaged zip file: bad central directory")
        entries += 1
        flags = le16(data, p + 8)
        method = le16(data, p + 10)
        crc = UInt32(le32(data, p + 16))
        compressed_size = le32(data, p + 20)
        uncompressed_size = le32(data, p + 24)
        name_length, extra_length, comment_length = le16(data, p + 28), le16(data, p + 30), le16(data, p + 32)
        header = le32(data, p + 42)  # where the file's local header starts
        p + 45 + name_length + extra_length + comment_length <= n || error("Damaged zip file: bad central directory")
        name = file_name(data[p+46:p+45+name_length])
        # A ZIP64 extra field (ID 1) holds, in this order, the sizes and offset
        # that are 0xffffffff here because they did not fit.
        q = p + 46 + name_length
        extra_end = q + extra_length
        while q + 3 < extra_end
            id, len = le16(data, q), le16(data, q + 2)
            if id == 1
                r = q + 4
                if uncompressed_size == 0xffffffff && r + 7 < extra_end
                    uncompressed_size = le64(data, r)
                    r += 8
                end
                if compressed_size == 0xffffffff && r + 7 < extra_end
                    compressed_size = le64(data, r)
                    r += 8
                end
                if header == 0xffffffff && r + 7 < extra_end
                    header = le64(data, r)
                end
                break
            end
            q += 4 + len
        end
        header += 1 + shift
        p += 46 + name_length + extra_length + comment_length

        (endswith(name, "/") || !keep(name)) && continue  # a folder, or a file not wanted
        flags & 0x0001 == 0 || error("Encrypted zip files are not supported: $name")
        (1 <= header <= n - 29 && le32(data, header) == 0x04034b50) ||
            error("Damaged zip file: no header for $name")
        first = header + 30 + le16(data, header + 26) + le16(data, header + 28)
        (0 <= compressed_size <= n - first + 1) || error("Damaged zip file: $name is cut off")
        raw = data[first:first+compressed_size-1]
        contents = if method == 0
            raw
        elseif method == 8
            try
                # At most one byte more than the file's size is decompressed, so
                # a damaged size cannot make it use far more memory than it says.
                # Deflate data cannot grow more than 1,032 times, which bounds a
                # damaged (or hostile) size in turn.
                limit = min(uncompressed_size, 1032 * length(raw) + 64) + 1
                read(InflateStream(IOBuffer(raw)), limit)
            catch err
                err isa InterruptException && rethrow()
                error("Damaged zip file: $name cannot be decompressed ($(sprint(showerror, err)))")
            end
        else
            error("Unsupported zip compression method $method for $name")
        end
        (length(contents) == uncompressed_size && crc32(contents) == crc) ||
            error("Damaged zip file: $name fails its CRC check")
        push!(files, name => contents)
    end
    (zip64 ? entries == count : entries % 65536 == count) ||
        error("Damaged zip file: its central directory lists $entries files, but its end record says $count")
    return files
end

end # module
