# Offline tests for the pure-Julia PDF and zip readers, src/PDFText.jl and
# src/ZipReader.jl. They build small PDFs and zip files in memory, so they
# need no network access. They run as part of the package's tests
# (test/runtests.jl), or on their own from the package folder with:
#
#     julia --project=. -e 'using Pkg; Pkg.instantiate()'   # once
#     julia --project=. test/readers.jl
#
# Citations:
#   Code generated by Claude Code, Anthropic, September 24, 2026, https://claude.ai/code/session_019awDnsGJAcXbzPNQg6VhqU.

using Test
include(joinpath(@__DIR__, "..", "src", "PDFText.jl"))
include(joinpath(@__DIR__, "..", "src", "ZipReader.jl"))

# ---------------------------------------------------------------------------
# Building test PDFs
# ---------------------------------------------------------------------------

"A PDF of the given objects, numbered from 1 (object 1 is the catalog), with a classic xref table."
function make_pdf(objects::Vector{String})
    io = IOBuffer()
    print(io, "%PDF-1.4\n")
    offsets = Int[]
    for (i, object) in enumerate(objects)
        push!(offsets, position(io))
        print(io, "$i 0 obj\n$object\nendobj\n")
    end
    xref = position(io)
    print(io, "xref\n0 $(length(objects) + 1)\n0000000000 65535 f \n")
    for offset in offsets
        print(io, lpad(offset, 10, '0'), " 00000 n \n")
    end
    print(io, "trailer\n<< /Size $(length(objects) + 1) /Root 1 0 R >>\nstartxref\n$xref\n%%EOF\n")
    return take!(io)
end

stream_object(content; dict = "") = "<< $dict /Length $(sizeof(content)) >>\nstream\n$content\nendstream"

# A Type 1 font whose glyphs from code 32 to 126 are all 500/1000 em wide.
const HELVETICA = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /FirstChar 32 /LastChar 126 /Widths [$(join(fill(500, 95), ' '))] >>"

"""
A one-page PDF drawing `content`. Objects 1 to 4 are the catalog, the page
tree (which holds the resources, so the page inherits them), the page and its
content; `extra` objects are numbered from 5.
"""
one_page(content; resources = "<< /Font << /F1 $HELVETICA >> >>", extra = String[]) = make_pdf([
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 /Resources $resources >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>",
    stream_object(content),
    extra...,
])

words(page) = [[w.text for w in line.words] for line in page]

# ---------------------------------------------------------------------------

@testset "PDFText" begin
    @testset "lines, words and positions" begin
        pdf = one_page("""
            BT /F1 10 Tf 36 700 Td (Bill Number) Tj 100 0 Td (HB2003) Tj ET
            BT /F1 10 Tf 36 680 Td [(Y) -2000 (FINAL)] TJ ET
            """)
        pages = PDFText.read_lines(pdf)
        @test length(pages) == 1
        @test words(pages[1]) == [["Bill", "Number", "HB2003"], ["Y", "FINAL"]]
        @test [line.y for line in pages[1]] ≈ [700, 680]
        bill = pages[1][1].words[3]
        @test bill.x ≈ 136 && bill.right ≈ 136 + 6 * 5
        # The TJ number moves FINAL right by 2000/1000 of the font size.
        @test pages[1][2].words[2].x ≈ 36 + 5 + 20
        @test PDFText.text(pages[1][1]) == "Bill Number HB2003"
    end

    @testset "string syntax" begin
        pdf = one_page("BT /F1 10 Tf 36 700 Td (a\\(b\\)c\\101\\\nd) Tj 0 -20 Td <48 49 4> Tj ET % a comment\n")
        @test words(PDFText.read_lines(pdf)[1]) == [["a(b)cAd"], ["HI@"]]
    end

    @testset "text state and matrices" begin
        pdf = one_page("""
            q 2 0 0 2 0 0 cm
            BT /F1 10 Tf 14 TL 10 300 Td (ab) Tj T* (cd) Tj (ef) ' 1 Tc 20 0 Td (gh) Tj ET
            Q
            BT /F1 10 Tf 50 Tz 100 100 Td (ij) Tj ET
            """)
        page = PDFText.read_lines(pdf)[1]
        @test words(page) == [["ab"], ["cd"], ["ef", "gh"], ["ij"]]
        @test [line.y for line in page] ≈ [600, 572, 544, 100]
        @test page[1].words[1].x ≈ 20 && page[1].words[1].right ≈ 40
        # Td moves from the start of the line; Tc adds 1 text space unit
        # (2 points, after the 2x cm) after each glyph.
        @test page[3].words[2].x ≈ 60 && page[3].words[2].right ≈ 60 + 10 + 2 + 10
        # Tz 50 halves the glyph widths.
        @test page[4].words[1].right ≈ 105
    end

    @testset "Type0 font, Identity-H, ToUnicode, /W and ligatures" begin
        cmap = """
            /CIDInit /ProcSet findresource begin 12 dict begin begincmap
            1 begincodespacerange <0000> <FFFF> endcodespacerange
            2 beginbfchar <0001> <0077> <0004> <FB01> endbfchar
            1 beginbfrange <0002> <0003> <0069> endbfrange
            1 beginbfrange <0005> <0006> [<D83DDE00> <00410042>] endbfrange
            endcmap CMapName currentdict /CMap defineresource pop end end
            """
        font = "<< /Type /Font /Subtype /Type0 /BaseFont /X /Encoding /Identity-H /ToUnicode 5 0 R " *
               "/DescendantFonts [<< /Type /Font /Subtype /CIDFontType2 /BaseFont /X /DW 500 /W [1 [600 700]] >>] >>"
        pdf = one_page("BT /F2 10 Tf 50 500 Td <0001000200030004> Tj 0 -20 Td <00050006> Tj ET";
                       resources = "<< /Font << /F2 $font >> >>", extra = [stream_object(cmap)])
        page = PDFText.read_lines(pdf)[1]
        @test words(page) == [["wijfi"], ["😀AB"]]
        # Widths: CID 1 is 600, CID 2 is 700, others the default 500.
        @test page[1].words[1].x ≈ 50 && page[1].words[1].right ≈ 50 + 6 + 7 + 5 + 5
    end

    @testset "simple font /Differences" begin
        font = "<< /Type /Font /Subtype /Type1 /BaseFont /Times-Roman " *
               "/Encoding << /Type /Encoding /Differences [65 /uni00E9 /quoteright /eacute] >> >>"
        # Code 0252 is quotedblleft in StandardEncoding, the base encoding of Type 1 fonts.
        pdf = one_page("BT /F3 10 Tf 36 700 Td (ABC\\252) Tj ET"; resources = "<< /Font << /F3 $font >> >>")
        @test words(PDFText.read_lines(pdf)[1]) == [["é’é“"]]
    end

    @testset "form XObjects and inline images" begin
        form = stream_object("BT /F1 10 Tf 0 0 Td (inside) Tj ET";
                             dict = "/Type /XObject /Subtype /Form /BBox [0 0 100 100] /Matrix [1 0 0 1 100 100] " *
                                    "/Resources << /Font << /F1 $HELVETICA >> >>")
        pdf = one_page("/Fm1 Do BI /W 2 /H 1 /BPC 8 /CS /G ID \x01EIx EI BT /F1 10 Tf 36 700 Td (after) Tj ET";
                       resources = "<< /XObject << /Fm1 5 0 R >> /Font << /F1 $HELVETICA >> >>", extra = [form])
        page = PDFText.read_lines(pdf)[1]
        @test words(page) == [["after"], ["inside"]]
        @test page[2].words[1].x ≈ 100 && page[2].y ≈ 100
    end

    @testset "damaged cross-reference data is rebuilt" begin
        pdf = one_page("BT /F1 10 Tf 36 700 Td (still here) Tj ET")
        s = String(copy(pdf))
        broken = Vector{UInt8}(replace(s, r"startxref\n\d+" => "startxref\n17"))
        @test words(PDFText.read_lines(broken)[1]) == [["still", "here"]]
    end

    @testset "xref stream and object stream" begin
        content = "BT /F1 10 Tf 36 700 Td (compressed objects) Tj ET"
        inner = ["<< /Type /Catalog /Pages 2 0 R >>",
                 "<< /Type /Pages /Kids [3 0 R] /Count 1 /Resources << /Font << /F1 $HELVETICA >> >> >>",
                 "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>"]
        body = join(inner, "\n")
        starts = cumsum([0; [sizeof(o) + 1 for o in inner[1:end-1]]])
        header = join(("$(i) $(starts[i])" for i in 1:3), " ") * "\n"
        io = IOBuffer()
        print(io, "%PDF-1.5\n")
        offsets = Dict{Int,Int}()
        offsets[4] = position(io)
        print(io, "4 0 obj\n", stream_object(content), "\nendobj\n")
        offsets[5] = position(io)
        print(io, "5 0 obj\n", stream_object(header * body; dict = "/Type /ObjStm /N 3 /First $(sizeof(header))"), "\nendobj\n")
        offsets[6] = position(io)
        entry(kind, a, b) = UInt8[kind; reinterpret(UInt8, [hton(UInt32(a))]); reinterpret(UInt8, [hton(UInt16(b))])]
        table = vcat(entry(0, 0, 65535), entry(2, 5, 0), entry(2, 5, 1), entry(2, 5, 2),
                     entry(1, offsets[4], 0), entry(1, offsets[5], 0), entry(1, offsets[6], 0))
        print(io, "6 0 obj\n<< /Type /XRef /Size 7 /W [1 4 2] /Root 1 0 R /Length $(length(table)) >>\nstream\n")
        write(io, table)
        print(io, "\nendstream\nendobj\nstartxref\n$(offsets[6])\n%%EOF\n")
        @test words(PDFText.read_lines(take!(io))[1]) == [["compressed", "objects"]]
    end

    @testset "FlateDecode and the PNG Up predictor" begin
        # zlib data for "hello hello hello hello, zip!" (made with Python's zlib).
        zlib = UInt8[0x78, 0xda, 0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0x57, 0xc8, 0x40, 0x27, 0x75, 0x14,
                     0xaa, 0x32, 0x0b, 0x14, 0x01, 0xa1, 0xf5, 0x0a, 0x71]
        doc = PDFText.Document(one_page(""))
        s = PDFText.Stream(Dict{Symbol,Any}(:Filter => :FlateDecode), zlib)
        @test String(PDFText.decode(doc, s)) == "hello hello hello hello, zip!"
        rows = UInt8[2, 1, 2, 3, 2, 1, 1, 1]
        params = Dict{Symbol,Any}(:Predictor => 12, :Columns => 3)
        @test PDFText.unpredict(doc, rows, params) == UInt8[1, 2, 3, 2, 3, 4]
    end

    @testset "other standard filters" begin
        doc = PDFText.Document(one_page(""))
        decode(filter, data; params = nothing) = PDFText.decode(doc, PDFText.Stream(
            Dict{Symbol,Any}(:Filter => filter, :DecodeParms => params), Vector{UInt8}(data)))
        # The LZW example of section 7.4.4.2.
        @test decode(:LZWDecode, UInt8[0x80, 0x0b, 0x60, 0x50, 0x22, 0x0c, 0x0c, 0x85, 0x01]) ==
              Vector{UInt8}("-----A---B")
        @test String(decode(:ASCII85Decode, "87cURD_*#4DfTZ)+T~>")) == "Hello, World!"
        @test decode(:ASCII85Decode, "z@:B~>") == UInt8[0, 0, 0, 0, UInt8('a'), UInt8('b')]
        @test String(decode(:ASCIIHexDecode, "48 65 6C6c 6F>")) == "Hello"
        @test String(decode(:RunLengthDecode, UInt8[0x02, 0x61, 0x62, 0x63, 0xfe, 0x78, 0x80])) == "abcxxx"
        # A Flate stream whose Adler-32 checksum is wrong is still read.
        zlib = UInt8[0x78, 0xda, 0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0x57, 0xc8, 0x40, 0x27, 0x75, 0x14,
                     0xaa, 0x32, 0x0b, 0x14, 0x01, 0xa1, 0xf5, 0x0a, 0x00]
        @test String(@test_logs((:warn,), decode(:FlateDecode, zlib))) == "hello hello hello hello, zip!"
    end

    @testset "encodings" begin
        @test length(PDFText.WIN_ANSI) == length(PDFText.STANDARD) == length(PDFText.MAC_ROMAN) == 256
        @test PDFText.MAC_ROMAN[0x8e+1] == "é" && PDFText.MAC_ROMAN[0xd2+1] == "“" && PDFText.MAC_ROMAN[0xff+1] == "ˇ"
        @test PDFText.STANDARD[0xb1+1] == "–" && PDFText.STANDARD[0x27+1] == "’"
        @test PDFText.glyph_text("udieresis") == "ü" && PDFText.glyph_text("germandbls") == "ß"
        @test PDFText.glyph_text("uni00410042") == "AB" && PDFText.glyph_text("u1F600") == "😀"
        @test PDFText.glyph_text("a.sc") == "a" && PDFText.glyph_text("notaglyph") == ""
    end

    @testset "standard 14 fonts without /Widths" begin
        # "illicit" is 1.888 em wide in Helvetica, not 7 x 0.5 em; with a guessed
        # width the next word would overlap it and the letters would interleave.
        helvetica = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        pdf = one_page("BT /F1 10 Tf 72 700 Td (illicit) Tj 22.67 0 Td (lilt) Tj ET";
                       resources = "<< /Font << /F1 $helvetica >> >>")
        page = PDFText.read_lines(pdf)[1]
        @test words(page) == [["illicit", "lilt"]]
        @test page[1].words[1].right ≈ 72 + 10 * (0.222 + 0.222 + 0.222 + 0.222 + 0.5 + 0.222 + 0.278)
        @test PDFText.standard_14_widths(:ArialMT) === PDFText.STANDARD_14_WIDTHS["Helvetica"]
        @test PDFText.standard_14_widths(Symbol("ABCDEF+TimesNewRomanPS-BoldItalicMT")) ===
              PDFText.STANDARD_14_WIDTHS["Times-BoldItalic"]
        @test PDFText.standard_14_widths(:Aptos) === nothing
    end

    @testset "rotated pages and text that is not horizontal" begin
        # /Rotate 90 with content drawn so that it reads upright in a viewer.
        pdf = make_pdf([
            "<< /Type /Catalog /Pages 2 0 R >>",
            "<< /Type /Pages /Kids [3 0 R] /Count 1 /Rotate 90 /Resources << /Font << /F1 $HELVETICA >> >> >>",
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>",
            stream_object("q 0 1 -1 0 612 0 cm BT /F1 10 Tf 72 500 Td (upright text) Tj ET Q"),
        ])
        page = PDFText.read_lines(pdf)[1]
        @test words(page) == [["upright", "text"]]
        @test page[1].words[1].x ≈ 72 && page[1].y ≈ 500
        # A diagonal watermark drawn over two lines is kept out of them.
        pdf = one_page("""
            BT /F1 10 Tf 36 500 Td (first line) Tj 0 -12 Td (second line) Tj ET
            BT /F1 20 Tf 0.7071 0.7071 -0.7071 0.7071 40 480 Tm (DRAFT) Tj ET
            """)
        @test words(PDFText.read_lines(pdf)[1]) == [["first", "line"], ["second", "line"], ["DRAFT"]]
    end

    @testset "text drawn twice to look bold" begin
        pdf = one_page("BT /F1 10 Tf 100 700 Td (Bold) Tj ET BT /F1 10 Tf 100.4 700 Td (Bold) Tj ET")
        @test words(PDFText.read_lines(pdf)[1]) == [["Bold"]]
    end

    @testset "hostile files end quickly" begin
        # A form XObject that draws itself.
        form = stream_object("BT /F1 10 Tf 100 600 Td (x) Tj ET " * "/X Do "^10;
                             dict = "/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources 6 0 R")
        pdf = one_page("/X Do"; resources = "6 0 R",
                       extra = [form, "<< /Font << /F1 $HELVETICA >> /XObject << /X 5 0 R >> >>"])
        @test words(PDFText.read_lines(pdf)[1]) == [["x"]]
        # Arrays nested 10,000 deep: the page's text before them is kept.
        pdf = one_page("BT /F1 10 Tf 36 700 Td (kept) Tj ET " * "["^10000)
        @test words(@test_logs((:warn,), match_mode = :any, PDFText.read_lines(pdf))[1]) == [["kept"]]
        # An xref subsection claiming a trillion entries.
        pdf = one_page("BT /F1 10 Tf 36 700 Td (fine) Tj ET")
        huge = Vector{UInt8}(replace(String(copy(pdf)), r"xref\n0 \d+" => "xref\n0 999999999999"))
        @test words(PDFText.read_lines(huge)[1]) == [["fine"]]
    end

    @testset "damaged or unusual parts of a file" begin
        # A page may have no /Contents at all; that is not damage.
        pdf = make_pdf(["<< /Type /Catalog /Pages 2 0 R >>",
                        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
                        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] >>"])
        @test (@test_logs PDFText.read_lines(pdf)) == [PDFText.Line[]]
        # A damaged /ToUnicode CMap is skipped, and the font's encoding used instead.
        font = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /ToUnicode 5 0 R >>"
        pdf = one_page("BT /F1 10 Tf 36 700 Td (still read) Tj ET";
                       resources = "<< /Font << /F1 $font >> >>",
                       extra = [stream_object("not zlib data"; dict = "/Filter /FlateDecode")])
        @test words(@test_logs((:warn,), match_mode = :any, PDFText.read_lines(pdf))[1]) == [["still", "read"]]
        # A damaged /Rotate is read as a real number rather than failing.
        pdf = make_pdf(["<< /Type /Catalog /Pages 2 0 R >>",
                        "<< /Type /Pages /Kids [3 0 R] /Count 1 /Resources << /Font << /F1 $HELVETICA >> >> >>",
                        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Rotate 99999999999999999999 /Contents 4 0 R >>",
                        stream_object("BT /F1 10 Tf 36 700 Td (upright) Tj ET")])
        @test words(PDFText.read_lines(pdf)[1]) == [["upright"]]
        @test PDFText.glyph_text("dmacron") == "đ" && PDFText.glyph_text("ldotaccent") == "ŀ"
    end

    @testset "a wrong offset for one object" begin
        pdf = one_page("BT /F1 10 Tf 36 700 Td (found anyway) Tj ET")
        s = String(copy(pdf))
        # The xref entry of object 4 (the content) points 3 bytes too far.
        offset = first(findfirst("4 0 obj", s)) - 1
        wrong = replace(s, lpad(offset, 10, '0') * " 00000 n" => lpad(offset + 3, 10, '0') * " 00000 n")
        doc = PDFText.Document(Vector{UInt8}(wrong))
        @test doc.scanned === nothing  # the xref itself was read, not rebuilt
        @test words(PDFText.read_lines(Vector{UInt8}(wrong))[1]) == [["found", "anyway"]]
    end

    @testset "clear errors" begin
        @test_throws ErrorException PDFText.read_lines(b"not a pdf"[:])
        pdf = one_page("")
        encrypted = Vector{UInt8}(replace(String(copy(pdf)), "/Root 1 0 R" => "/Root 1 0 R /Encrypt << >>"))
        @test_throws ErrorException PDFText.read_lines(encrypted)
    end
end

# ---------------------------------------------------------------------------
# Building test zip files
# ---------------------------------------------------------------------------

le16(x) = reinterpret(UInt8, [htol(UInt16(x))])
le32(x) = reinterpret(UInt8, [htol(UInt32(x))])

"""
A zip of `(name, stored bytes, method, uncompressed bytes)` entries. With
`descriptor`, the local headers leave the sizes and CRC at 0 (flag bit 3), as
zip tools do when they write to a stream.
"""
function make_zip(entries; descriptor = false)
    io = IOBuffer()
    central = IOBuffer()
    for (name, stored, method, contents) in entries
        offset = position(io)
        crc = ZipReader.crc32(contents)
        flags = descriptor ? 0x0008 : 0x0000
        local_sizes = descriptor ? (0, 0, 0) : (crc, length(stored), length(contents))
        write(io, le32(0x04034b50), le16(20), le16(flags), le16(method), le16(0), le16(0),
              le32(local_sizes[1]), le32(local_sizes[2]), le32(local_sizes[3]),
              le16(sizeof(name)), le16(0), codeunits(name), stored)
        descriptor && write(io, le32(0x08074b50), le32(crc), le32(length(stored)), le32(length(contents)))
        write(central, le32(0x02014b50), le16(20), le16(20), le16(flags), le16(method), le16(0), le16(0),
              le32(crc), le32(length(stored)), le32(length(contents)), le16(sizeof(name)), le16(0), le16(0),
              le16(0), le16(0), le32(0), le32(offset), codeunits(name))
    end
    start = position(io)
    cd = take!(central)
    write(io, cd, le32(0x06054b50), le16(0), le16(0), le16(length(entries)), le16(length(entries)),
          le32(length(cd)), le32(start), le16(0))
    return take!(io)
end

le64(x) = reinterpret(UInt8, [htol(UInt64(x))])

"""
A ZIP64 zip of stored `(name, contents)` entries: the central directory's sizes
and offsets are 0xffffffff with their values in ZIP64 extra fields, and the end
record's numbers are in a ZIP64 end record. `count` overrides the end record's
count.
"""
function make_zip64(entries; count = length(entries))
    io, central = IOBuffer(), IOBuffer()
    for (name, contents) in entries
        offset = position(io)
        crc = ZipReader.crc32(contents)
        write(io, le32(0x04034b50), le16(45), le16(0), le16(0), le16(0), le16(0), le32(crc),
              le32(length(contents)), le32(length(contents)), le16(sizeof(name)), le16(0), codeunits(name), contents)
        extra = [le16(1); le16(24); le64(length(contents)); le64(length(contents)); le64(offset)]
        write(central, le32(0x02014b50), le16(45), le16(45), le16(0), le16(0), le16(0), le16(0), le32(crc),
              le32(0xffffffff), le32(0xffffffff), le16(sizeof(name)), le16(length(extra)), le16(0),
              le16(0), le16(0), le32(0), le32(0xffffffff), codeunits(name), extra)
    end
    start = position(io)
    cd = take!(central)
    record = start + length(cd)
    write(io, cd, le32(0x06064b50), le64(44), le16(45), le16(45), le32(0), le32(0), le64(count), le64(count),
          le64(length(cd)), le64(start), le32(0x07064b50), le32(0), le64(record), le32(1),
          le32(0x06054b50), le16(0), le16(0), le16(0xffff), le16(0xffff), le32(0xffffffff), le32(0xffffffff), le16(0))
    return take!(io)
end

@testset "ZipReader" begin
    @test ZipReader.crc32(codeunits("The quick brown fox jumps over the lazy dog")) == 0x414fa339

    text = Vector{UInt8}("hello hello hello hello, zip!")
    # Raw Deflate data for `text` (made with Python's zlib).
    deflated = UInt8[0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0x57, 0xc8, 0x40, 0x27, 0x75, 0x14, 0xaa, 0x32, 0x0b, 0x14, 0x01]
    entries = [("folder/", UInt8[], 0, UInt8[]),
               ("folder/stored.txt", Vector{UInt8}("stored"), 0, Vector{UInt8}("stored")),
               ("déflaté.txt", deflated, 8, text)]
    for descriptor in (false, true)
        files = ZipReader.read_zip(make_zip(entries; descriptor = descriptor))
        @test files == ["folder/stored.txt" => Vector{UInt8}("stored"), "déflaté.txt" => text]
    end

    # Something before the archive (such as a self-extracting program) moves every offset.
    zip = make_zip(entries)
    @test ZipReader.read_zip([Vector{UInt8}("#!/bin/sh a program\n"); zip]) == ZipReader.read_zip(zip)
    # An archive comment that looks like the end of central directory record.
    fake = [zip[1:end-2]; le16(26); Vector{UInt8}("PK\x05\x06"); zeros(UInt8, 18); Vector{UInt8}("more")]
    @test ZipReader.read_zip(fake) == ZipReader.read_zip(zip)
    # Names that are not UTF-8 are code page 437.
    @test ZipReader.file_name(UInt8[0x4d, 0x81, 0x6c, 0x6c, 0x65, 0x72]) == "Müller"

    # ZIP64, with and without a program before it (whose length the locator's offset leaves out).
    small = ["a.txt" => Vector{UInt8}("first"), "b/c.bin" => UInt8[0, 1, 2, 255]]
    zip64 = make_zip64(small)
    @test ZipReader.read_zip(zip64) == small
    @test ZipReader.read_zip([Vector{UInt8}("#!/bin/sh a program\n"); zip64]) == small
    # An end record whose count does not match the central directory.
    @test_throws ErrorException ZipReader.read_zip(make_zip64(small; count = 1))
    @test_throws ErrorException ZipReader.read_zip(make_zip64(small; count = 0))

    damaged = make_zip([("a.txt", Vector{UInt8}("abc"), 0, Vector{UInt8}("abd"))])
    @test_throws ErrorException ZipReader.read_zip(damaged)
    @test_throws ErrorException ZipReader.read_zip(Vector{UInt8}("not a zip file at all, just text"))
    @test_throws ErrorException ZipReader.read_zip(make_zip([("a.bin", UInt8[1, 2], 12, UInt8[1, 2])]))
    # Files left out by `keep` are not decompressed, so their method does not matter.
    mixed = make_zip([("readme.txt", UInt8[1, 2], 12, UInt8[1, 2]), ("a.pdf", Vector{UInt8}("%PDF"), 0, Vector{UInt8}("%PDF"))])
    @test ZipReader.read_zip(mixed; keep = path -> endswith(path, ".pdf")) == ["a.pdf" => Vector{UInt8}("%PDF")]
end
